---
title: "Maps"
author: "Grace Rade"
date: "2023-03-24"
output: html_document
---
```{r}
library(tidyverse)
library(sf)
library(readr)
library(urbnmapr)
library(wesanderson)
library(usmap)
```

```{r}
## loading in the map of the US and convert to an sf object
USA_map <-  maps::map("state", plot = FALSE, fill = TRUE)

USA_sf <- USA_map %>% 
  st_as_sf(crs = 4326) %>% 
  mutate(State = str_to_title(ID))

## load in the dataset

data <- read.csv("datasets/all_risk_set.csv")

## states only for merging later
states <- data %>% 
  distinct(State)
 ## only one of each plz

## finding the number of policies enacted by each state for total and direction
risk_set <- data %>% 
  group_by(State) %>% 
  summarize(NumTot = sum(Policy)) ## get the number of policies enacted by a state

risk_set_pos <- read.csv("datasets/all_risk_set.csv") %>% 
  filter(Direction == "P" | is.na(Direction)) %>% 
  group_by(State) %>% 
  summarize(NumPos = sum(Policy)) %>% 
  full_join(states)  

risk_set_pos$NumPos[is.na(risk_set_pos$NumPos)] <- 0

risk_set_neg <- read.csv("datasets/all_risk_set.csv") %>% 
  filter(Direction == "N" | is.na(Direction)) %>% 
  group_by(State) %>% 
  summarize(NumNeg = sum(Policy)) %>% 
  full_join(states)  

risk_set_neg$NumNeg[is.na(risk_set_neg$NumNeg)] <- 0

## bring it all together bby
risks_total <- risk_set %>% 
  full_join(risk_set_pos) %>% 
  full_join(risk_set_neg) %>% 
  rename(state = "State")
```

```{r}
## joinging the datasets; it's all coming together now
state_risks <- risks_total %>% 
  left_join(USA_sf, by = "State") %>% 
  as.data.frame()
```

```{r}

## making the map bby
ggplot(data = state_risks, aes(geometry = geom)) +
  geom_sf(mapping = aes(fill = NumTot), color = "#ffffff") + labs(fill = "Nummber of Policies") +
  ggtitle("Total Number of LGBTQ Education Policies 1987-2022")

## jesus this won't work ugghhhhhhhhhhhhhhhhhhhhhhhhh

## positive policies
ggplot(data = state_risks, aes(geometry = geom)) +
  geom_sf(mapping = aes(fill = NumPos), color = "#ffffff") + labs(fill = "Nummber of Policies") +
  ggtitle("Total Number of Positive LGBTQ Education Policies 1987-2022")

## negative policies
ggplot(data = state_risks, aes(geometry = geom)) +
  geom_sf(mapping = aes(fill = NumNeg), color = "#ffffff") + labs(fill = "Nummber of Policies") +
  ggtitle("Total Number of Negative LGBTQ Education Policies 1987-2022")
```

```{r}
## new maps with the different package, includes alaska and hawaii

plot_usmap(region = "states", data = risks_total, values = 'NumTot') + 
  scale_fill_continuous(name = "Number of Policies", low = "#56B1F7", high = "#132B43") +
  labs(title =  "Total Number of LGBTQ Education Policy Adoptions by State") +
  theme(legend.position = "right") ## i did some googling to find the exact colors, source: https://ggplot2.tidyverse.org/reference/scale_gradient.html for the default values to switch them so lighter is less

plot_usmap(region = "states", data = risks_total, values = 'NumPos') + 
  scale_fill_continuous(name = "Number of Policies", low = "#56B1F7", high = "#132B43") +
  labs(title =  "Total Number of Positive LGBTQ Education Policy Adoptions by State") +
  theme(legend.position = "right") ## positive policies

plot_usmap(region = "states", data = risks_total, values = 'NumNeg') + 
  scale_fill_continuous(name = "Number of Policies", low = "#56B1F7", high = "#132B43") +
  labs(title =  "Total Number of Negative LGBTQ Education Policy Adoptions by State") +
  theme(legend.position = "right") ## negative policies
```

