---
title: "Bathroom_Ban_RiskSet"
author: "Grace Rade"
date: "2022-12-07"
output: html_document
---
```{r}
library(tidyverse)
library(rio)
require(lme4)

bathroom_ban <- read.csv("datasets/LawsPolicies.csv") %>% 
  filter(Category == "Bathroom ban ") %>% 
  mutate(Adoption_Year = Year) %>% 
  select(-c(Description, X, Month, Day, Date, Year)) 

bathroom_ban$State[bathroom_ban$State == "Oklahoma "] <- "Oklahoma"
  
empty_data <- read.csv("datasets/EmptyData2.csv")


### generate binary indicator for adoption, that way each state has at most 1 adoption
bathroom_risk_set <- empty_data %>% 
  left_join(bathroom_ban)%>% 
     mutate(Adoption_Year = replace_na(Adoption_Year, 2022)) %>%
     mutate(Policy= if_else(Adoption_Year == Year, 1, 0)) %>%
     filter(Adoption_Year>=Year)
 
bathroom_risk_set$Category[is.na(bathroom_risk_set$Category)] <- "Bathroom ban "
```



```{r}
### Sample code for estimating model with state level data
#### This is already EHA form data

state_data_eha <- import("datasets/digital_eha.dta") 
### Adoption is a binary indicator, using logit to predict
m1 <- glm(adoption~ std_population+std_mass_ideology+unified+std_income+ std_legp_squire, data=state_data_eha, family=binomial)

summary(m1)


state_data_eha$policyno <- as.factor(state_data_eha$policyno)
### if we want to add random effects by policy
### with so many policies, this may take a while (usually a few minutes)
m2 <- glmer(adoption~ std_population+std_mass_ideology+unified+std_income+ std_legp_squire+ (1|policy), data=state_data_eha, family=binomial)

summary(m2)


#### state_data.dta has lots of controls/other variables up through 2019
### NOTE- you will need to rename the variable State to statename (abbreviation is state)
```

```{r}
export(bathroom_risk_set, "bathroom_risk_set.csv")
```

