---
title: "NewRiskSet"
author: "Grace Rade"
date: "2023-06-08"
output: html_document
---
```{r}
## loading packages
library(tidyverse)
library(haven)
library(rio)
library(janitor)
library(labelled)

policy_risk_set <- import("./datasets/all_risk_set.csv") %>% 
  clean_names() %>% 
  rename(state_name = "state") %>% 
  mutate(state_name = str_squish(toupper(state_name))) ## the risk set of all the policies w/o covariates

state_names <- import("./datasets/ces_data.dta") %>% 
  select(-inputstate) %>% 
  rename(evangelical_pop = "pew_bornagain") %>% 
  mutate(evangelical_pop = as.numeric(evangelical_pop*100), state = str_squish(state), state_name = str_squish(state_name)) ## name file for all + evangelical data

var_label(state_names$evangelical_pop) <- NULL ## get rid of the variable label
attributes(state_names$year) <- NULL ## remove all attributes
state_names$state_name[state_names$state_name == ""] <- NA ## sub out empties for NAs


#remove_attributes(state_names, "format.stata")

just_names <- state_names %>%
  select(c(state, state_name)) %>% 
  distinct() ## get just the name variables

names2014 <- state_names %>% 
  select(state_name, state) %>% 
  distinct() %>% 
  mutate(year = 2014) %>% 
  filter(!is.na(state_name)) %>% 
  filter(state_name != "DISTRICT OF COLUMBIA") ## filling in the full state names for 2014


names2015 <- state_names %>% 
  select(state_name, state) %>% 
  distinct() %>% 
  mutate(year = 2015) %>% 
  filter(!is.na(state_name)) %>% 
  filter(state_name != "DISTRICT OF COLUMBIA") ## filling in the full state names for 2015

#state_names <- state_names %>% 
 # full_join(names2014) %>% 
 # full_join(names2015)

race_health <- import("./datasets/race_health_data.dta") %>% 
  mutate(state_name = str_squish(toupper(state_name))) ## covariates

expanded_years <- import("./datasets/expanded_years.dta") %>% 
  mutate(incomepcap = floor(income), statenam = str_squish(toupper(statenam))) %>% 
  rename(state_name = "statenam") ## expanded years covariates

state_data <- import("./datasets/state_data.dta") %>% 
  mutate(state_name = str_squish(toupper(state_name))) ## more covariates

risk_set <- policy_risk_set %>% ## join the risk set to the name file
  ## at this point there are no missing values in the state-name or state variables
  left_join(race_health) %>% 
  left_join(expanded_years) ## get all the covariates in


evangelical1 <- import("./datasets/evangelical_pop data.csv") %>% 
  rename(state = "st", state_name = "state") %>% 
  mutate(state_name = str_squish(toupper(state_name))) %>% 
  select(-c(state_fips, state_icpsr, stateno, V1)) ## first evangelical dataset

evangelical1 <- evangelical1 %>% 
  full_join(state_names) %>% 
  filter(year >= 1987, state != "DC") %>% 
  filter(!is.na(evangelical_pop))  ## trying to get the missing statenames to fill in (failure, why)

risk_set <- risk_set %>% 
  left_join(evangelical1) %>% 
  select(state, statename, year, policy, category, direction, adoption_year, population_total, pollib_median, incomepcap, std_bowen1, std_bowen2, unified, std_init_use, evangelical_pop) ## covairiates with the names fixed

## export(risk_set, "new_risk.csv")
  

```

```{r}
## let's see if we can fill anything in now

## population (from the )

library(tidycensus)

population2019 <- read_csv("./datasets/nst-est2019-alldata.csv") ## population estimates 2010-2019

population2019 <- population2019 %>% 
  filter(!row_number() %in% c(1:5)) ## get rid of rows I don't want at the top

population2019_2 <- population2019 %>% 
  filter(!STATE %in% c(11, 72)) %>%  ## get rid of rando rows I don't want
  clean_names() %>%  
  rename(state_name = "name", state_num = "state") %>%
  select(state_num, state_name, popestimate2015, popestimate2016, popestimate2017, popestimate2018, popestimate2019) %>% ## select variables I want
  mutate(state_name = str_squish(toupper(state_name))) %>% ## get state names all uppsercase to match
  left_join(unique(just_names)) ## join the state code variable

population2019_2 <- population2019_2 %>% 
  mutate(year2015 = 2015, year2016 = 2016, year2017 = 2017, year2018 = 2018, year2019 = 2019) ## making the year variable

population2015 <- population2019_2 %>% 
  select(state, state_name, year2015, popestimate2015) %>% ## select the cols i want
  rename(year = "year2015", population_total = "popestimate2015") ## rename

population2016 <-  population2019_2 %>% 
  select(state, state_name, year2016, popestimate2016) %>% 
  rename(year = "year2016", population_total = "popestimate2016")

population2017 <- population2019_2 %>% 
  select(state, state_name, year2017, popestimate2017) %>% 
  rename(year = "year2017", population_total = "popestimate2017")

population2018 <- population2019_2 %>% 
  select(state, state_name, year2018, popestimate2018) %>% 
  rename(year = "year2018", population_total = "popestimate2018")

population22001199 <- population2019_2 %>% 
  select(state, state_name, year2019, popestimate2019) %>% 
  rename(year = "year2019", population_total = "popestimate2019")

population2019 <- population2015 %>% 
  full_join(population2016) %>% 
  full_join(population2017) %>% 
  full_join(population2018) %>% 
  full_join(population22001199) ## got the population data all set for 2015-2019


population2022 <- read_csv("./datasets/NST-EST2022-ALLDATA.csv") ## population data 2020-2022

population2022 <- population2022 %>% 
  filter(!row_number() %in% c(1:14)) ## remove rows i don't want

population2022 <- population2022 %>% 
  filter(!STATE %in% c(11, 72)) %>%  ## get rid of rando rows I don't want
  clean_names() %>%  
  rename(state_name = "name", state_num = "state") ## rename vars to match 

population2022 <- population2022 %>% 
  select(state_num, state_name, popestimate2020, popestimate2021, popestimate2022) %>% 
  mutate(state_name = str_squish(toupper(state_name))) %>% ## get state names all uppsercase to match
  left_join(unique(just_names))

population2020 <- population2022 %>% 
  select(state, state_name, popestimate2020) %>% ## select the vars i want
  rename(population_total = "popestimate2020") %>% ## rename variable
  mutate(year = 2020) ## add year variable

population2021 <- population2022 %>% 
  select(state, state_name, popestimate2021) %>% 
  rename(population_total = "popestimate2021") %>% 
  mutate(year = 2021)

population2022_2 <- population2022 %>% 
  select(state, state_name, state_num, popestimate2022) %>% 
  rename(population_total = "popestimate2022") %>% 
  mutate(year = 2022)

population2022 <- population2020 %>% 
  full_join(population2021) %>% 
  full_join(population2022_2) ##joining 2020, 2021, 2022

population2022 <- population2019 %>% 
  full_join(population2022) ## joining 2015-2019 with 2020-2022

#export(population2022, "population2015_2019.csv"). ## exporting the dataset
```

```{r}

## don't run this chunk

## evangelical population (from the cooperative election survey)

evangelical2022_2 <- import("./datasets/CES2022_clean.csv") ## evangelical data 2022

# evangelical2022 <- evangelical2022 %>% 
#   select(inputstate, pew_bornagain, commonweight) %>%
#   rename(state_num = 'inputstate') %>% 
#   mutate(state_num = as.character(state_num))
# 
# ## converting the state numbers to match population df
# evangelical2022$state_num[evangelical2022$state_num == "1"] <- "01"
# evangelical2022$state_num[evangelical2022$state_num == "2"] <- "02"
# evangelical2022$state_num[evangelical2022$state_num == "3"] <- "03"
# evangelical2022$state_num[evangelical2022$state_num == "4"] <- "04"
# evangelical2022$state_num[evangelical2022$state_num == "5"] <- "05"
# evangelical2022$state_num[evangelical2022$state_num == "6"] <- "06"
# evangelical2022$state_num[evangelical2022$state_num == "7"] <- "07"
# evangelical2022$state_num[evangelical2022$state_num == "8"] <- "08"
# evangelical2022$state_num[evangelical2022$state_num == "9"] <- "09"

number_of_states <- evangelical2022_2 %>% 
  group_by(as.numeric(state_num)) %>% 
  summarize(n()) ## checking for stuff idk

evangelical2022 <- evangelical2022_2 %>% 
  mutate(state_num = as.character(state_num)) %>% 
  full_join(population2022_2) ## why is this not all of the states (AL, AK, AZ, AR, CA, CO, CT excluded somehow), might be a problem with the merging (cries)


weights <- evangelical2022 %>% 
  group_by(state) %>% 
  summarize(weight = mean(commonweight)) %>% 
  filter(!is.na(state))

attempted_collapse <- evangelical2022 %>% 
  group_by(state, pew_bornagain) %>% 
  summarize(num = n()) %>% 
  full_join(weights) %>% ##summarizing the weights (idk if this is right)
  group_by(state) %>% ##group by state again (weight variable should be statewide not state-answer)
  mutate(total = sum(num), evangelical_pop = ((num/(total)*weight)*100)) %>% ## get the percent evangelical (idk if this is right)
  filter(pew_bornagain == "1", !is.na(state)) %>%  ## getting rid of NAs and born again = 2 (no)
  mutate(year = 2022)

## mean weight is correct, but it needs to be by state
attempted_collapse

#export(attempted_collapse, "evangelical2022.csv") 2022 only, for Scott
#export(evangelical2022, "CES2022_clean.csv") cleaned data, only the vars we need
```

```{r}
## evangelical 2021 data (from the cooperative election survey)

## load the r data file (why are they like this it's harvard come on)
evangelical2021 <- as.data.frame(table)

str(evangelical2021)

evangelical2021 <- evangelical2021 %>% 
  select(inputstate, pew_bornagain, commonweight) %>%
  rename(state_num = 'inputstate') %>% 
  mutate(state_num = as.character(state_num))

## converting the state numbers to match population df
evangelical2021$state_num[evangelical2021$state_num == "1"] <- "01"
evangelical2021$state_num[evangelical2021$state_num == "2"] <- "02"
evangelical2021$state_num[evangelical2021$state_num == "3"] <- "03"
evangelical2021$state_num[evangelical2021$state_num == "4"] <- "04"
evangelical2021$state_num[evangelical2021$state_num == "5"] <- "05"
evangelical2021$state_num[evangelical2021$state_num == "6"] <- "06"
evangelical2021$state_num[evangelical2021$state_num == "7"] <- "07"
evangelical2021$state_num[evangelical2021$state_num == "8"] <- "08"
evangelical2021$state_num[evangelical2021$state_num == "9"] <- "09"

## get rid of attributes
attributes(evangelical2021$pew_bornagain) <- NULL
attributes(evangelical2021$commonweight) <- NULL

## join with population to get all the state ID vars
evangelical2021 <- evangelical2021 %>% 
  full_join(population2022_2) %>% 
  select(-c(population_total, year))

weights2021 <- evangelical2021 %>% 
  group_by(state) %>% 
  summarize(weight = mean(commonweight)) %>% 
  filter(!is.na(state))

attempted_collapse2021 <- evangelical2021 %>% 
  group_by(state, pew_bornagain) %>% 
  summarize(num = n()) %>% 
  full_join(weights) %>% ##summarizing the weights (idk if this is right)
  group_by(state) %>% ##group by state again (weight variable should be statewide not state-answer)
  mutate(total = sum(num), evangelical_pop = ((num/(total)*weight)*100)) %>% ## get the percent evangelical (idk if this is right)
  filter(pew_bornagain == "1", !is.na(state)) %>% 
  mutate(year = 2021)

## join 2021 and 2022
evangelical2122 <- attempted_collapse %>% 
  full_join(attempted_collapse2021) %>% 
  filter(state != "")

## export(evangelical2122, "evangelical2021_2011.csv") ## export it 
```

```{r}
## incomepcap (from US Dept. of Commerce Bureau of Economic Analysis )

incomepcap <- import("./datasets/income20112022.csv") ## import the dataset

incomepcap <- incomepcap %>% 
  rename(state_name = "GeoName") ## rename the name variable

incomepcap <- incomepcap %>% 
  filter(GeoFips != 0 & GeoFips != 11000) %>% ## drop the rows I don't want 
  select(-GeoFips) ## drop the variable I don't want

incomepcap <- incomepcap %>% 
  mutate(state_name = str_squish(toupper(state_name))) %>% ## match the state name when i merge
  left_join(just_names) %>% ## bring in state variable
  clean_names() ## clean names (why are they just numbers)

income2011 <- incomepcap %>% 
  select(state, state_name, x2011) %>% ## select the stuff for just the year i want
  rename(incomepcap = 'x2011') %>% ## rename to match risk set
  mutate(year = 2011) ## add year

income2012 <- incomepcap %>% 
  select(state, state_name, x2012) %>% 
  rename(incomepcap = 'x2012') %>% 
  mutate(year = 2012) ## repeating to 2012

income2013 <- incomepcap %>% 
  select(state, state_name, x2013) %>% 
  rename(incomepcap = 'x2013') %>% 
  mutate(year = 2013) ## repeating to 2013

income2014 <- incomepcap %>% 
  select(state, state_name, x2014) %>% 
  rename(incomepcap = 'x2014') %>% 
  mutate(year = 2014) ## repeating to 2014

income2015 <- incomepcap %>% 
  select(state, state_name, x2015) %>% 
  rename(incomepcap = 'x2015') %>% 
  mutate(year = 2015) ## repeating to 2015

income2016 <- incomepcap %>% 
  select(state, state_name, x2016) %>% 
  rename(incomepcap = 'x2016') %>% 
  mutate(year = 2016) ## repeating to 2016

income2017 <- incomepcap %>% 
  select(state, state_name, x2017) %>% 
  rename(incomepcap = 'x2017') %>% 
  mutate(year = 2017) ## repeating to 2017

income2018 <- incomepcap %>% 
  select(state, state_name, x2018) %>% 
  rename(incomepcap = 'x2018') %>% 
  mutate(year = 2018) ## repeating to 2018

income2019 <- incomepcap %>% 
  select(state, state_name, x2019) %>% 
  rename(incomepcap = 'x2019') %>% 
  mutate(year = 2019) ## repeating to 2019

income2020 <- incomepcap %>% 
  select(state, state_name, x2020) %>% 
  rename(incomepcap = 'x2020') %>% 
  mutate(year = 2020) ## repeating to 2020

income2021 <- incomepcap %>% 
  select(state, state_name, x2021) %>% 
  rename(incomepcap = 'x2021') %>% 
  mutate(year = 2021) ## repeating to 2021

income2022 <- incomepcap %>% 
  select(state, state_name, x2022) %>% 
  rename(incomepcap = 'x2022') %>% 
  mutate(year = 2022) ## repeating to 2022

incomepcap11_22 <- income2011 %>% ## join them all
  full_join(income2012) %>% 
  full_join(income2013) %>% 
  full_join(income2014) %>% 
  full_join(income2015) %>% 
  full_join(income2016) %>% 
  full_join(income2017) %>% 
  full_join(income2018) %>% 
  full_join(income2019) %>% 
  full_join(income2020) %>% 
  full_join(income2021) %>% 
  full_join(income2022)

## export(incomepcap11_22, "incomepcap2011_2022.csv") ## export
```

```{r}
## get just he populations for each year and state

risk_states <- import("./datasets/new_risk.csv") 
population <- risk_states %>% 
  select(year, statename, population_total) ## select cols I want
population <- population %>% 
  mutate(statename = str_squish(toupper(statename))) %>% ## fix names
  rename(state_name = "statename") %>% ## make variables match
  distinct() ## get rid fo extras

population_all <- population2022 %>% 
  select(state_name, year, population_total) %>% ## drop the state abbrev. var and state number
  full_join(population) %>% ## join with the big risk set
  filter(!is.na(population_total)) %>% ## get rid of the NA population/no state name
  arrange(year) # sort by year

pop_check <- population_all %>% 
  group_by(year) %>% 
  summarise(n()) ## check to see if there is 50 per year

# export(population_all, "population_only2022.csv")

```

```{r}
## demographic data

census_dems <- import("./datasets/ACSDP1Y2021.DP05-2023-07-26T164727.csv") ## import the census bureau data 

check_race <- import("./datasets/race_health_data.dta") ## load in the existing data to check for coverage

check_race <- check_race %>% 
  select(state, statenam, pctblack, year) %>% 
  filter(year >= 1987, is.na(pctblack)) ## check for percent black coverage

check_sex <- race_health %>% 
  select(state, statenam, popfemale, year) %>% 
  filter(year >= 1987, is.na(popfemale)) ## check for female population coverage


## testing out the procedure 

census_dems2 <- census_dems %>% ## starting with making a new df
  select(`Label (Grouping)`, `SEX AND AGE!!Total population`) %>% ## select cols of interest (this is just a test)
  rename(state_name = "Label (Grouping)", sex = "SEX AND AGE!!Total population") ## rename cause ew

census_dems2 <- census_dems2 %>% 
  mutate(state_name = str_squish(toupper(state_name))) %>% ## fix the state name vairable to get rid of spaces and lowercase
  filter(state_name != "PERCENT") %>% ## filter the percents
  mutate(sex = ifelse(sex == "", NA, sex)) %>% ## get rid of empty cells
  fill(sex, .direction = c("up")) %>% ## fill the empty (slay)
  filter(state_name != "ESTIMATE") ## get rid of duplicate rows

## white population 2021
census_dems2021 <- census_dems %>% 
  select(`Label (Grouping)`, `RACE!!Total population!!One race!!White`, `HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)`, `RACE!!Total population!!One race!!Black or African American`, `SEX AND AGE!!Total population!!Female`) %>% ## select vars
  rename(state_name = "Label (Grouping)", white_pop = "RACE!!Total population!!One race!!White", black_pop = "RACE!!Total population!!One race!!Black or African American", hispanic_pop = "HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)", female_pop = "SEX AND AGE!!Total population!!Female") ## rename vars

census_dems2021 <- census_dems2021 %>% 
  mutate(state_name = str_squish(toupper(state_name))) %>% ## fix the state name vairable to get rid of spaces and lowercase
  filter(state_name != "PERCENT") %>% ## dump percent
  mutate(white_pop = ifelse(white_pop == "", NA, white_pop), black_pop = ifelse(black_pop == "", NA, black_pop), hispanic_pop = ifelse(hispanic_pop == "", NA, hispanic_pop), female_pop = ifelse(female_pop == "", NA, female_pop)) %>% ## get rid of empty cells
  fill(white_pop, black_pop, hispanic_pop, female_pop, .direction = "up") %>% ## fill!
  filter(state_name != "ESTIMATE") ## ok so this works for multipe vars, maybe a loop is not needed IDK

census_dems2021 <- census_dems2021 %>% 
  filter(!state_name %in% c("DISTRICT OF COLUMBIA", "PUERTO RICO"))  %>% ## drop PR and DC (sorry)
  mutate(year = 2021)
```

```{r}
## lets work on a loop 

census_names <- list.files("./datasets/census/", full.names = TRUE) ## a list of the names 

## ok i'm not sure that this is working, will check back later but i'mjust going to do it manually becuase they keep 
for (data in census_names){
 data = import(data) 
 data = data %>% 
   select(`Label (Grouping)`, `RACE!!One race!!White`, `HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)`, `RACE!!One race!!Black or African American`, `SEX AND AGE!!Total population!!Female`) %>% ## select vars
  rename(state_name = "Label (Grouping)", white_pop = "RACE!!One race!!White", black_pop = "RACE!!One race!!Black or African American", hispanic_pop = "HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)", female_pop = "SEX AND AGE!!Total population!!Female")
 
 data = data %>% 
   mutate(state_name = str_squish(toupper(state_name))) %>% ## fix the state name vairable to get rid of spaces and lowercase
  filter(state_name != "PERCENT") %>% ## dump percent
  mutate(white_pop = ifelse(white_pop == "", NA, white_pop), black_pop = ifelse(black_pop == "", NA, black_pop), hispanic_pop = ifelse(hispanic_pop == "", NA, hispanic_pop), female_pop = ifelse(female_pop == "", NA, female_pop)) %>% ## get rid of empty cells
  fill(white_pop, black_pop, hispanic_pop, female_pop, .direction = "up") %>% ## fill!
  filter(state_name != "ESTIMATE")
 
 data = data %>% 
   filter(!state_name %in% c("DISTRICT OF COLUMBIA", "PUERTO RICO")) ## drop PR and DC (sorry)
}

## i think the loop isn't working because the tables aren't the same year after year (fuck the census bureau for that)
```

```{r}
## census data, sans loop

## 2015
census2015 <- import("./datasets/census/census2015.csv") ## import it

census2015 <- census2015 %>% 
  select(`Label (Grouping)`, `RACE!!One race!!White`, `HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)`, `RACE!!One race!!Black or African American`, `SEX AND AGE!!Total population!!Female`) %>% ## select vars
  rename(state_name = "Label (Grouping)", white_pop = "RACE!!One race!!White", black_pop = "RACE!!One race!!Black or African American", hispanic_pop = "HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)", female_pop = "SEX AND AGE!!Total population!!Female")

census2015 <- census2015 %>% 
   mutate(state_name = str_squish(toupper(state_name))) %>% ## fix the state name vairable to get rid of spaces and lowercase
  filter(state_name != "PERCENT") %>% ## dump percent
  mutate(white_pop = ifelse(white_pop == "", NA, white_pop), black_pop = ifelse(black_pop == "", NA, black_pop), hispanic_pop = ifelse(hispanic_pop == "", NA, hispanic_pop), female_pop = ifelse(female_pop == "", NA, female_pop)) %>% ## get rid of empty cells
  fill(white_pop, black_pop, hispanic_pop, female_pop, .direction = "up") %>% ## fill!
  filter(state_name != "ESTIMATE")

census2015 <- census2015 %>% 
  filter(!state_name %in% c("DISTRICT OF COLUMBIA", "PUERTO RICO")) %>% ## filter out PR and DC
  mutate(year = 2015) ## add the year 


## 2016
census2016 <- import("./datasets/census/census2016.csv")

census2016 <- census2016 %>% 
  select(`Label (Grouping)`, `RACE!!One race!!White`, `HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)`, `RACE!!One race!!Black or African American`, `SEX AND AGE!!Total population!!Female`) %>% ## select vars
  rename(state_name = "Label (Grouping)", white_pop = "RACE!!One race!!White", black_pop = "RACE!!One race!!Black or African American", hispanic_pop = "HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)", female_pop = "SEX AND AGE!!Total population!!Female")

census2016 <- census2016 %>% 
   mutate(state_name = str_squish(toupper(state_name))) %>% ## fix the state name vairable to get rid of spaces and lowercase
  filter(state_name != "PERCENT") %>% ## dump percent
  mutate(white_pop = ifelse(white_pop == "", NA, white_pop), black_pop = ifelse(black_pop == "", NA, black_pop), hispanic_pop = ifelse(hispanic_pop == "", NA, hispanic_pop), female_pop = ifelse(female_pop == "", NA, female_pop)) %>% ## get rid of empty cells
  fill(white_pop, black_pop, hispanic_pop, female_pop, .direction = "up") %>% ## fill!
  filter(state_name != "ESTIMATE")

census2016 <- census2016 %>% 
  filter(!state_name %in% c("DISTRICT OF COLUMBIA", "PUERTO RICO")) %>% ## filter out PR and DC
  mutate(year = 2016) 

## 2017

census2017 <- import("./datasets/census/census2017.csv")

census2017 <- census2017 %>% 
  select(`Label (Grouping)`, `RACE!!One race!!White`, `HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)`, `RACE!!One race!!Black or African American`, `SEX AND AGE!!Total population!!Female`) %>% ## select vars
  rename(state_name = "Label (Grouping)", white_pop = "RACE!!One race!!White", black_pop = "RACE!!One race!!Black or African American", hispanic_pop = "HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)", female_pop = "SEX AND AGE!!Total population!!Female")

census2017 <- census2017 %>% 
   mutate(state_name = str_squish(toupper(state_name))) %>% ## fix the state name vairable to get rid of spaces and lowercase
  filter(state_name != "PERCENT") %>% ## dump percent
  mutate(white_pop = ifelse(white_pop == "", NA, white_pop), black_pop = ifelse(black_pop == "", NA, black_pop), hispanic_pop = ifelse(hispanic_pop == "", NA, hispanic_pop), female_pop = ifelse(female_pop == "", NA, female_pop)) %>% ## get rid of empty cells
  fill(white_pop, black_pop, hispanic_pop, female_pop, .direction = "up") %>% ## fill!
  filter(state_name != "ESTIMATE")

census2017 <- census2017 %>% 
  filter(!state_name %in% c("DISTRICT OF COLUMBIA", "PUERTO RICO")) %>% ## filter out PR and DC
  mutate(year = 2017)

## 2018

census2018 <- import("./datasets/census/census2018.csv")

census2018 <- census2018 %>% 
  select(`Label (Grouping)`, `RACE!!Total population!!One race!!White`, `HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)`, `RACE!!Total population!!One race!!Black or African American`, `SEX AND AGE!!Total population!!Female`) %>% ## select vars
  rename(state_name = "Label (Grouping)", white_pop = "RACE!!Total population!!One race!!White", black_pop = "RACE!!Total population!!One race!!Black or African American", hispanic_pop = "HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)", female_pop = "SEX AND AGE!!Total population!!Female")

census2018 <- census2018 %>% 
   mutate(state_name = str_squish(toupper(state_name))) %>% ## fix the state name vairable to get rid of spaces and lowercase
  filter(state_name != "PERCENT") %>% ## dump percent
  mutate(white_pop = ifelse(white_pop == "", NA, white_pop), black_pop = ifelse(black_pop == "", NA, black_pop), hispanic_pop = ifelse(hispanic_pop == "", NA, hispanic_pop), female_pop = ifelse(female_pop == "", NA, female_pop)) %>% ## get rid of empty cells
  fill(white_pop, black_pop, hispanic_pop, female_pop, .direction = "up") %>% ## fill!
  filter(state_name != "ESTIMATE")

census2018 <- census2018 %>% 
  filter(!state_name %in% c("DISTRICT OF COLUMBIA", "PUERTO RICO")) %>% ## filter out PR and DC
  mutate(year = 2018)

## 2019 

census2019 <- import("./datasets/census/census2019.csv")

census2019 <- census2019 %>% 
  select(`Label (Grouping)`, `RACE!!Total population!!One race!!White`, `HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)`, `RACE!!Total population!!One race!!Black or African American`, `SEX AND AGE!!Total population!!Female`) %>% ## select vars
  rename(state_name = "Label (Grouping)", white_pop = "RACE!!Total population!!One race!!White", black_pop = "RACE!!Total population!!One race!!Black or African American", hispanic_pop = "HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)", female_pop = "SEX AND AGE!!Total population!!Female")

census2019 <- census2019 %>% 
   mutate(state_name = str_squish(toupper(state_name))) %>% ## fix the state name vairable to get rid of spaces and lowercase
  filter(state_name != "PERCENT") %>% ## dump percent
  mutate(white_pop = ifelse(white_pop == "", NA, white_pop), black_pop = ifelse(black_pop == "", NA, black_pop), hispanic_pop = ifelse(hispanic_pop == "", NA, hispanic_pop), female_pop = ifelse(female_pop == "", NA, female_pop)) %>% ## get rid of empty cells
  fill(white_pop, black_pop, hispanic_pop, female_pop, .direction = "up") %>% ## fill!
  filter(state_name != "ESTIMATE")

census2019 <- census2019 %>% 
  filter(!state_name %in% c("DISTRICT OF COLUMBIA", "PUERTO RICO")) %>% ## filter out PR and DC
  mutate(year = 2019)

## now let's try to get some percentages with state population

census_dems20152021 <- census2015 %>% 
  full_join(census2016) %>% 
  full_join(census2017) %>% 
  full_join(census2018) %>% 
  full_join(census2019) %>% 
  full_join(census_dems2021) ## join them all together

census_dems20152021  <- census_dems20152021 %>% 
  left_join(population2022) ## join with population

census_dems20152021 <- census_dems20152021 %>% 
  select(-state_num) ## deselect the column that i don't need
  
census_dems20152021 <- census_dems20152021 %>% 
  mutate(female_pop = as.numeric(gsub(",", "", census_dems20152021$female_pop)), white_pop = as.numeric(gsub(",", "", census_dems20152021$white_pop)), black_pop = as.numeric(gsub(",", "", census_dems20152021$black_pop)), hispanic_pop = as.numeric(gsub(",", "", census_dems20152021$hispanic_pop))) %>% 
  mutate(pct_black = black_pop/population_total, pct_white = white_pop/population_total, pct_hispanic = hispanic_pop/population_total, pct_female = female_pop/population_total, pct_male = 1 - pct_female) ## boom we got it but no 2020 though, have to track that down separately


## export(census_dems20152021, "census_dems20152021.csv") ## export


## let's get some more years (2010-2014)
## these get tricky ughhhhhhh i hate the census bureau

## 2010
census2010 <- import("./datasets/census/census2010.csv")

census2010 <- census2010[, !duplicated(colnames(census2010))] ## get rid of duplicate columns

census2010 <- census2010 %>% 
   select(`Label (Grouping)`, `RACE!!One race!!White`, `HISPANIC OR LATINO AND RACE!!Hispanic or Latino (of any race)`, `SEX AND AGE!!Female`) %>% ## select vars
  rename(state_name = "Label (Grouping)", white_pop = "RACE!!One race!!White",  hispanic_pop = "HISPANIC OR LATINO AND RACE!!Hispanic or Latino (of any race)", female_pop = "SEX AND AGE!!Female")

census2010 <- census2010 %>% 
  mutate(state_name = str_squish(toupper(state_name))) %>% ## fix the state name vairable to get rid of spaces and lowercase
  filter(state_name != "PERCENT") %>% ## dump percent
  mutate(white_pop = ifelse(white_pop == "", NA, white_pop), hispanic_pop = ifelse(hispanic_pop == "", NA, hispanic_pop), female_pop = ifelse(female_pop == "", NA, female_pop)) %>% ## get rid of empty cells
  fill(white_pop, hispanic_pop, female_pop, .direction = "up") %>% ## fill!
  filter(state_name != "ESTIMATE")

census2010 <- census2010 %>% 
  filter(!state_name %in% c("DISTRICT OF COLUMBIA", "PUERTO RICO")) %>% ## filter out PR and DC
  mutate(year = 2010)

census2010 <- census2010 %>% 
  mutate(white_pop = as.numeric(gsub(",", "", census2010$white_pop)), hispanic_pop = as.numeric(gsub(",", "", census2010$hispanic_pop)), female_pop = as.numeric(gsub(",", "", census2010$female_pop))) ## make everything numeric

census2010 <- census2010 %>% 
  left_join(population) %>% 
  mutate(pct_white = white_pop/population_total, pct_hispanic = hispanic_pop/population_total, pct_female = female_pop/population_total) %>% 
  select(-population_total)

## 2011 (i figured this one out by myself slayyyyyyy)

census2011 <- import("./datasets/census/census2011.csv")

census2011 <- census2011[, !duplicated(colnames(census2011))] ## get rid of duplicate 

census2011 <- census2011 %>% select(`Label (Grouping)`, `SEX AND AGE!!Total population`, `RACE!!One race!!White`, `HISPANIC OR LATINO AND RACE!!Hispanic or Latino (of any race)`, `SEX AND AGE!!Female`) %>% ## select vars
  rename(state_name = "Label (Grouping)", white_pop = "RACE!!One race!!White",  hispanic_pop = "HISPANIC OR LATINO AND RACE!!Hispanic or Latino (of any race)", female_pop = "SEX AND AGE!!Female", total_pop = "SEX AND AGE!!Total population")

census2011 <- census2011 %>% 
  mutate(state_name = str_squish(toupper(state_name))) %>% ## fix the state name vairable to get rid of spaces and lowercase
  filter(!total_pop %in% c("c", "(X)"), !state_name %in% c("2011 - 2009 STATISTICAL SIGNIFICANCE", "2011 - 2008 STATISTICAL SIGNIFICANCE", "2011 - 2007 STATISTICAL SIGNIFICANCE")) %>% ## dump percent
  mutate(white_pop = ifelse(white_pop == "", NA, white_pop), hispanic_pop = ifelse(hispanic_pop == "", NA, hispanic_pop), female_pop = ifelse(female_pop == "", NA, female_pop), total_pop = ifelse(total_pop == "", NA, total_pop)) %>% ## get rid of empty cells
  fill(total_pop, white_pop, hispanic_pop, female_pop, .direction = "up") %>% ## fill!
  filter(!state_name %in% c("2011 ESTIMATE", "2010 ESTIMATE", "DISTRICT OF COLUMBIA", "PUERTO RICO")) ## filter extra rows

census2011 <- census2011 %>% 
  mutate(female_pop = as.numeric(gsub("%", "", census2011$female_pop)), white_pop = as.numeric(gsub("%", "", census2011$white_pop)), total_pop = as.numeric(gsub(",", "", census2011$total_pop)), hispanic_pop = as.numeric(gsub("%", "", census2011$hispanic_pop))) %>% ## make numeric and get rid of unwanted characters
  mutate(pct_white = white_pop/100, pct_female = female_pop/100, pct_hispanic = hispanic_pop/100) %>% ## percentage vars
  mutate(white_pop = total_pop*pct_white, female_pop = total_pop*pct_female, hispanic_pop = total_pop*pct_hispanic) ## get whole number population values

census2011 <- census2011 %>% 
  mutate(year = 2011) ## add year

## 2012

census2012 <- import("./datasets/census/census2012.csv")

census2012 <- census2012[, !duplicated(colnames(census2012))] ## get rid of duplicate cols

census2012 <- census2012 %>% 
  select(`Label (Grouping)`, `SEX AND AGE!!Total population`, `RACE!!One race!!White`, `HISPANIC OR LATINO AND RACE!!Hispanic or Latino (of any race)`, `SEX AND AGE!!Female`) %>% ## select vars
  rename(state_name = "Label (Grouping)", white_pop = "RACE!!One race!!White",  hispanic_pop = "HISPANIC OR LATINO AND RACE!!Hispanic or Latino (of any race)", female_pop = "SEX AND AGE!!Female", total_pop = "SEX AND AGE!!Total population")

census2012 <- census2012 %>% 
  mutate(state_name = str_squish(toupper(state_name))) %>% ## fix the state name vairable to get rid of spaces and lowercase
  filter(!total_pop %in% c("c", "(X)"), !state_name %in% c("2012 - 2010 STATISTICAL SIGNIFICANCE", "2012 - 2011 STATISTICAL SIGNIFICANCE", "2012 - 2009 STATISTICAL SIGNIFICANCE", "2012 - 2008 STATISTICAL SIGNIFICANCE")) %>% ## dump percent
  mutate(white_pop = ifelse(white_pop == "", NA, white_pop), hispanic_pop = ifelse(hispanic_pop == "", NA, hispanic_pop), female_pop = ifelse(female_pop == "", NA, female_pop), total_pop = ifelse(total_pop == "", NA, total_pop)) %>% ## get rid of empty cells
  fill(total_pop, white_pop, hispanic_pop, female_pop, .direction = "up") %>% ## fill!
  filter(!state_name %in% c("2011 ESTIMATE", "2010 ESTIMATE", "2012 ESTIMATE", "DISTRICT OF COLUMBIA", "PUERTO RICO")) ## filter extra rows

census2012 <- census2012 %>% 
  mutate(female_pop = as.numeric(gsub("%", "", census2012$female_pop)), white_pop = as.numeric(gsub("%", "", census2012$white_pop)), total_pop = as.numeric(gsub(",", "", census2012$total_pop)), hispanic_pop = as.numeric(gsub("%", "", census2012$hispanic_pop))) %>% ## make numeric and get rid of unwanted characters
  mutate(pct_white = white_pop/100, pct_female = female_pop/100, pct_hispanic = hispanic_pop/100) %>% ## percentage vars
  mutate(white_pop = total_pop*pct_white, female_pop = total_pop*pct_female, hispanic_pop = total_pop*pct_hispanic)

census2012 <- census2012 %>% 
  mutate(year = 2012) ## add year

## 2013

census2013 <- import("./datasets/census/census2013.csv")

census2013 <- census2013[, !duplicated(colnames(census2013))] ## get rid of duplicate cols

census2013 <- census2013 %>% 
  select(`Label (Grouping)`, `SEX AND AGE!!Total population`, `RACE!!One race!!White`, `HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)`, `SEX AND AGE!!Total population!!Female`) %>% ## select vars
  rename(state_name = "Label (Grouping)", white_pop = "RACE!!One race!!White",  hispanic_pop = "HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)", female_pop = "SEX AND AGE!!Total population!!Female", total_pop = "SEX AND AGE!!Total population")

census2013 <- census2013 %>% 
   mutate(state_name = str_squish(toupper(state_name))) %>% ## fix the state name vairable to get rid of spaces and lowercase
  filter(!total_pop %in% c("c", "(X)"), !state_name %in% c("2012 - 2010 STATISTICAL SIGNIFICANCE", "2012 - 2011 STATISTICAL SIGNIFICANCE", "2012 - 2009 STATISTICAL SIGNIFICANCE", "2013 - 2009 STATISTICAL SIGNIFICANCE", "2012 ESTIMATE", "2011 ESTIMATE", "2010 ESTIMATE")) %>% ## dump percent
  mutate(white_pop = ifelse(white_pop == "", NA, white_pop), hispanic_pop = ifelse(hispanic_pop == "", NA, hispanic_pop), female_pop = ifelse(female_pop == "", NA, female_pop), total_pop = ifelse(total_pop == "", NA, total_pop)) %>% ## get rid of empty cells
  fill(total_pop, white_pop, hispanic_pop, female_pop, .direction = "up") %>% ## fill!
  filter(!state_name %in% c("2011 ESTIMATE", "2010 ESTIMATE", "2013 ESTIMATE", "DISTRICT OF COLUMBIA", "PUERTO RICO"))

census2013 <- census2013 %>% 
  mutate(female_pop = as.numeric(gsub("%", "", census2013$female_pop)), white_pop = as.numeric(gsub("%", "", census2013$white_pop)), total_pop = as.numeric(gsub(",", "", census2013$total_pop)), hispanic_pop = as.numeric(gsub("%", "", census2013$hispanic_pop))) %>% ## make numeric and get rid of unwanted characters
  mutate(pct_white = white_pop/100, pct_female = female_pop/100, pct_hispanic = hispanic_pop/100) %>% ## percentage vars
  mutate(white_pop = total_pop*pct_white, female_pop = total_pop*pct_female, hispanic_pop = total_pop*pct_hispanic)

census2013 <- census2013 %>% 
  mutate(year = 2013) ## add year

## 2014 

census2014 <- import("./datasets/census/census2014.csv")

census2014 <- census2014[, !duplicated(colnames(census2014))] ## get rid of duplicate cols

census2014 <- census2014 %>% 
  select(`Label (Grouping)`, `SEX AND AGE!!Total population`, `RACE!!One race!!White`, `HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)`, `SEX AND AGE!!Total population!!Female`) %>% ## select vars
  rename(state_name = "Label (Grouping)", white_pop = "RACE!!One race!!White",  hispanic_pop = "HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)", female_pop = "SEX AND AGE!!Total population!!Female", total_pop = "SEX AND AGE!!Total population")

census2014 <- census2014 %>% 
  mutate(state_name = str_squish(toupper(state_name))) %>% ## fix the state name vairable to get rid of spaces and lowercase
  filter(!total_pop %in% c("c", "(X)"), !state_name %in% c("2014 - 2013 STATISTICAL SIGNIFICANCE", "2014 - 2012 STATISTICAL SIGNIFICANCE", "2014 - 2011 STATISTICAL SIGNIFICANCE", "2014 - 2010 STATISTICAL SIGNIFICANCE", "2012 ESTIMATE", "2011 ESTIMATE", "2010 ESTIMATE", "2013 ESTIMATE")) %>% ## dump percent
  mutate(white_pop = ifelse(white_pop == "", NA, white_pop), hispanic_pop = ifelse(hispanic_pop == "", NA, hispanic_pop), female_pop = ifelse(female_pop == "", NA, female_pop), total_pop = ifelse(total_pop == "", NA, total_pop)) %>% ## get rid of empty cells
  fill(total_pop, white_pop, hispanic_pop, female_pop, .direction = "up") %>% ## fill!
  filter(!state_name %in% c("2014 ESTIMATE", "DISTRICT OF COLUMBIA", "PUERTO RICO"))

census2014 <- census2014 %>% 
  mutate(female_pop = as.numeric(gsub("%", "", census2014$female_pop)), white_pop = as.numeric(gsub("%", "", census2014$white_pop)), total_pop = as.numeric(gsub(",", "", census2014$total_pop)), hispanic_pop = as.numeric(gsub("%", "", census2014$hispanic_pop))) %>% ## make numeric and get rid of unwanted characters
  mutate(pct_white = white_pop/100, pct_female = female_pop/100, pct_hispanic = hispanic_pop/100) %>% ## percentage vars
  mutate(white_pop = total_pop*pct_white, female_pop = total_pop*pct_female, hispanic_pop = total_pop*pct_hispanic)

census2014 <- census2014 %>% 
  mutate(year = 2014)

## merge it all together

census1014 <- census2010 %>% 
  full_join(census2011) %>% 
  full_join(census2012) %>% 
  full_join(census2013) %>% 
  full_join(census2014) %>%
  full_join(crosswalk) %>% 
  select(-c(total_pop, stateno, state_icpsr)) %>%  ## get rid of total population
  mutate(pct_male = 1 - pct_female)

census1021 <- census1014 %>% 
  full_join(census_dems20152021) %>% ## merge the crosswalk file
  select(-population_total) ## get rid of population total

## export(census1021, "census1021.csv") ## export for 2010-2021

correlates <- import("./datasets/correlates_demographics.csv") ## import the correlates of state policy data

correlates2 <- correlates %>% 
  left_join(population) %>% ## join with the population data
  mutate(female_pop = ifelse(is.na(female_pop), 0, female_pop), male_pop = ifelse(is.na(male_pop), 0, male_pop), pct_hispanic = ifelse(is.na(pct_hispanic), 0, pct_hispanic), pct_white = ifelse(is.na(pct_white), 0, pct_white)) ## replace NAs with 0s for the math

correlates2 <- correlates2 %>% 
  mutate(pct_white = pct_white/100, pct_hispanic = pct_hispanic/100) %>% ## convert to decimals
  mutate(white_pop = pct_white*population_total, hispanic_pop = pct_hispanic*population_total, pct_female = female_pop/population_total, pct_male = male_pop/population_total)  ## get the pct and pop vars that are missing

## replace 0s back with NAs
correlates2$female_pop[correlates2$female_pop == 0] <- NA
correlates2$pct_female[correlates2$pct_female == 0] <- NA
correlates2$male_pop[correlates2$male_pop == 0] <- NA
correlates2$pct_male[correlates2$pct_male == 0] <- NA
correlates2$pct_white[correlates2$pct_white == 0] <- NA
correlates2$white_pop[correlates2$white_pop == 0] <- NA
correlates2$hispanic_pop[correlates2$hispanic_pop == 0] <- NA
correlates2$pct_hispanic[correlates2$pct_hispanic == 0] <- NA

correlates3 <- state_data %>% 
  select(state_name, year, pctblack) %>% ## get the beginning few years of pct_black
  rename(pct_black = "pctblack") %>% 
  left_join(population) %>% ## population totals
  left_join(crosswalk) %>% ## crosswalk file <3
  filter(year >= 1987) ## filter years for risk set

correlates3 <- correlates3 %>% 
  mutate(black_pop = pct_black*population_total) ## get black population

census_dems3 <- correlates2 %>% 
  full_join(correlates3) %>%  ## join pct_black with filled in CSP data for demographics
  full_join(census1021) %>%  ## join with the census demographics
  select(-stateno) ## get rid of var i don't want

## export(census_dems3, "population_demographics8720.csv") ## export
```

```{r}
## lets standardize the initiatives

inits_exist <- state_data %>% 
  select(state, state_name, init, initiatives, year) %>%  ## there are two intitiative variables so I'm just doing both
  mutate(state_name = str_squish(toupper(state_name))) ## match them names bby

inits_new <- import("./datasets/init_data.csv") ## import the new stuff

inits_new <- inits_new %>% 
  mutate(init = num_init, state_name = str_squish(toupper(state_name))) %>% ## fix them names bby and duplicate some columns
  rename("initiatives" = num_init) ## rename so i have the duplicates

inits <- inits_exist %>% 
  full_join(inits_new) %>% ##full join
  select(-c(state_fips, state_num, state_icpsr)) ## drop the columns that don't fill in from the crosswalk file

inits <- inits %>% 
  mutate(initiaitves = as.numeric(initiatives), mean = mean(initiatives, na.rm = T), sd = sd(initiatives, na.rm = T), std_init_use = (initiatives - mean)/sd) ## calculate the new columns: mean, sd, std_init_use (completely recalculated)

#export(inits, "initiatives2023.csv") ## export
```

```{r}
## policy liberalism

crosswalk <- import("./datasets/state_codes.csv") ## import the crosswalk file

pollib_raw <- read_dta("./datasets/CaugheyWarshaw_DynamicDemocracyAmericanStates_Export_2021.dta") ## read in updated policy liberalism data

pollib_raw <- pollib_raw %>% 
  select(abb, year, policy_updated) %>% ## select vars
  rename(state = "abb", pollib_median = "policy_updated") ## rename to match existing var name

pollib_raw <- pollib_raw %>% 
  filter(year >= 1987, state != "DC") ## filter out DC and years we already have

pollib_raw <- pollib_raw %>% 
  left_join(crosswalk) ## join with the crosswalk file for all the state ID vars

pollib_raw <- pollib_raw %>% 
  mutate(state_name = str_squish(toupper(state_name))) ## make uppercase, get rid of extra spaces


# crosswalk <- crosswalk %>% 
#   mutate(statenam = str_squish(toupper(statenam))) %>% 
#   rename(state_name = 'statenam')  %>% ## fix the crosswalk file for state name case and var name
#   filter(!is.na(stateno))

## export(crosswalk, "state_codes.csv") ## export the fixed crosswalk file as the same file name (overwrite slay)

## export(pollib_raw, "pollib_median8720.csv") ## export pollib data

```

```{r}
## education time

## 2010
education2010 <- import("./datasets/education/education2010.csv") ## import 

education2010 <- education2010 %>% 
  clean_names() ## clean names to make them unique

education2010 <- education2010 %>% 
  select(-c(poverty_rate_for_the_population_25_years_and_over_for_whom_poverty_status_is_determined_by_educational_attainment_level, poverty_rate_for_the_population_25_years_and_over_for_whom_poverty_status_is_determined_by_educational_attainment_level_less_than_high_school_graduate, poverty_rate_for_the_population_25_years_and_over_for_whom_poverty_status_is_determined_by_educational_attainment_level_high_school_graduate_includes_equivalency, poverty_rate_for_the_population_25_years_and_over_for_whom_poverty_status_is_determined_by_educational_attainment_level_bachelors_degree_or_higher, poverty_rate_for_the_population_25_years_and_over_for_whom_poverty_status_is_determined_by_educational_attainment_level_bachelors_degree_or_higher, median_earnings_in_the_past_12_months_in_2010_inflation_adjusted_dollars, median_earnings_in_the_past_12_months_in_2010_inflation_adjusted_dollars_population_25_years_and_over_with_earnings, median_earnings_in_the_past_12_months_in_2010_inflation_adjusted_dollars_less_than_high_school_graduate, median_earnings_in_the_past_12_months_in_2010_inflation_adjusted_dollars_high_school_graduate_includes_equivalency, median_earnings_in_the_past_12_months_in_2010_inflation_adjusted_dollars_some_college_or_associates_degree, median_earnings_in_the_past_12_months_in_2010_inflation_adjusted_dollars_bachelors_degree, median_earnings_in_the_past_12_months_in_2010_inflation_adjusted_dollars_graduate_or_professional_degree, percent_imputed, percent_imputed_educational_attainment, less_than_high_school_graduate, less_than_9th_grade, x9th_to_12th_grade_no_diploma, poverty_rate_for_the_population_25_years_and_over_for_whom_poverty_status_is_determined_by_educational_attainment_level_some_college_or_associates_degree)) ## get rid of the vars I don't want

education2010 <- education2010 %>% 
  rename(state_name = "label_grouping") ## rename

education2010 <- education2010 %>% 
  mutate(state_name = str_squish(toupper(state_name))) %>% ## fix the names
  filter(state_name != "TOTAL") %>% ## get rid of total rows
  mutate(population_18_to_24_years = ifelse(population_18_to_24_years == "", NA, population_18_to_24_years), 
         high_school_graduate_includes_equivalency = ifelse(high_school_graduate_includes_equivalency == "", NA, high_school_graduate_includes_equivalency), 
         some_college_or_associates_degree = ifelse(some_college_or_associates_degree == "", NA, some_college_or_associates_degree), 
         bachelors_degree_or_higher = ifelse(bachelors_degree_or_higher == "", NA, bachelors_degree_or_higher),
         population_25_years_and_over = ifelse(population_25_years_and_over == "", NA, population_25_years_and_over), 
         high_school_graduate_includes_equivalency_2 = ifelse(high_school_graduate_includes_equivalency_2 == "", NA, high_school_graduate_includes_equivalency_2), 
         some_college_no_degree = ifelse(some_college_no_degree == "", NA, some_college_no_degree), 
         associates_degree = ifelse(associates_degree == "", NA, associates_degree), 
         bachelors_degree = ifelse(bachelors_degree == "", NA, bachelors_degree), 
         graduate_or_professional_degree = ifelse(graduate_or_professional_degree == "", NA, graduate_or_professional_degree), 
         percent_high_school_graduate_or_higher = ifelse(percent_high_school_graduate_or_higher == "", NA, percent_high_school_graduate_or_higher), 
         percent_bachelors_degree_or_higher = ifelse(percent_bachelors_degree_or_higher == "", NA, percent_bachelors_degree_or_higher), 
         population_25_to_34_years = ifelse(population_25_to_34_years == "", NA, population_25_to_34_years), 
         high_school_graduate_or_higher = ifelse(high_school_graduate_or_higher == "", NA, high_school_graduate_or_higher), 
         bachelors_degree_or_higher_2 = ifelse(bachelors_degree_or_higher_2 == "", NA, bachelors_degree_or_higher_2), 
         population_35_to_44_years = ifelse(population_35_to_44_years == "", NA, population_35_to_44_years), 
         high_school_graduate_or_higher_2 = ifelse(high_school_graduate_or_higher_2 == "", NA, high_school_graduate_or_higher_2), 
         bachelors_degree_or_higher_3 = ifelse(bachelors_degree_or_higher_3 == "", NA, bachelors_degree_or_higher_3), 
         population_45_to_64_years = ifelse(population_45_to_64_years == "", NA, population_45_to_64_years),
         high_school_graduate_or_higher_3 = ifelse(high_school_graduate_or_higher_3 == "", NA, high_school_graduate_or_higher_3), 
         bachelors_degree_or_higher_4 = ifelse(bachelors_degree_or_higher_4 == "", NA, bachelors_degree_or_higher_4), 
         population_65_years_and_over = ifelse(population_65_years_and_over == "", NA, population_65_years_and_over), 
         high_school_graduate_or_higher_4 = ifelse(high_school_graduate_or_higher_4 == "", NA, high_school_graduate_or_higher_4), 
         bachelors_degree_or_higher_5 = ifelse(bachelors_degree_or_higher_5 == "", NA, bachelors_degree_or_higher_5)) %>% ## replace empty quotes with NAs
  fill(population_18_to_24_years, high_school_graduate_includes_equivalency, some_college_or_associates_degree, bachelors_degree_or_higher, population_25_years_and_over, high_school_graduate_includes_equivalency_2, some_college_no_degree, associates_degree, bachelors_degree, graduate_or_professional_degree, percent_high_school_graduate_or_higher, percent_bachelors_degree_or_higher, population_25_to_34_years, high_school_graduate_or_higher, bachelors_degree_or_higher_2, population_35_to_44_years, high_school_graduate_or_higher_2, bachelors_degree_or_higher_3, population_45_to_64_years, high_school_graduate_or_higher_3, bachelors_degree_or_higher_4, population_65_years_and_over, high_school_graduate_or_higher_4, bachelors_degree_or_higher_5, .direction = "up") ## fill everything up

education2010 <- education2010 %>% 
  filter(!state_name %in% c("ESTIMATE", "MALE", "FEMALE", "PUERTO RICO", "DISTRICT OF COLUMBIA")) ## filter unwanted rows

education2010 <- education2010 %>% ## convert everything to numeric (ugh this is tedious)
  mutate(population_18_to_24_years = as.numeric(gsub(",", "", education2010$population_18_to_24_years)),
         population_25_years_and_over = as.numeric(gsub(",", "", education2010$population_25_years_and_over)), 
         population_25_to_34_years = as.numeric(gsub(",", "", education2010$population_25_to_34_years)),
         population_35_to_44_years = as.numeric(gsub(",", "", education2010$population_35_to_44_years)), 
         population_45_to_64_years = as.numeric(gsub(",", "", education2010$population_45_to_64_years)), 
         population_65_years_and_over = as.numeric(gsub(",", "", education2010$population_65_years_and_over)), 
         high_school_graduate_includes_equivalency = as.numeric(gsub("%", "", education2010$high_school_graduate_includes_equivalency))/100, some_college_or_associates_degree = as.numeric(gsub("%", "", education2010$some_college_or_associates_degree))/100, 
         bachelors_degree_or_higher = as.numeric(gsub("%", "", education2010$bachelors_degree_or_higher))/100, 
         high_school_graduate_includes_equivalency_2 = as.numeric(gsub("%", "", education2010$high_school_graduate_includes_equivalency_2))/100, 
         some_college_no_degree = as.numeric(gsub("%", "", education2010$some_college_no_degree))/100, 
         associates_degree = as.numeric(gsub("%", "", education2010$associates_degree))/100, 
         bachelors_degree = as.numeric(gsub("%", "", education2010$bachelors_degree))/100,
         graduate_or_professional_degree = as.numeric(gsub("%", "", education2010$graduate_or_professional_degree))/100, 
         percent_high_school_graduate_or_higher = as.numeric(gsub("%", "", education2010$percent_high_school_graduate_or_higher))/100, 
         percent_bachelors_degree_or_higher = as.numeric(gsub("%", "", education2010$percent_bachelors_degree_or_higher))/100, 
         high_school_graduate_or_higher = as.numeric(gsub("%", "", education2010$high_school_graduate_or_higher))/100,
         bachelors_degree_or_higher_2 = as.numeric(gsub("%", "", education2010$bachelors_degree_or_higher_2))/100, 
         high_school_graduate_or_higher_2 = as.numeric(gsub("%", "", education2010$high_school_graduate_or_higher_2))/100, 
         bachelors_degree_or_higher_3 = as.numeric(gsub("%", "", education2010$bachelors_degree_or_higher_3))/100, 
         high_school_graduate_or_higher_3 = as.numeric(gsub("%", "", education2010$high_school_graduate_or_higher_3))/100, 
         bachelors_degree_or_higher_4 = as.numeric(gsub("%", "", education2010$bachelors_degree_or_higher_4))/100, 
         high_school_graduate_or_higher_4 = as.numeric(gsub("%", "", education2010$high_school_graduate_or_higher_4))/100, 
         bachelors_degree_or_higher_5 = as.numeric(gsub("%", "", education2010$bachelors_degree_or_higher_5))) ## converting everything to numeric (whew that was a lot)

education2010 <- education2010 %>% 
  mutate(high_school_graduate_includes_equivalency = high_school_graduate_includes_equivalency*population_18_to_24_years, percent_high_school_graduate_or_higher = percent_high_school_graduate_or_higher*population_25_years_and_over, bachelors_degree = bachelors_degree_or_higher*population_18_to_24_years, percent_bachelors_degree_or_higher = percent_bachelors_degree_or_higher*population_25_years_and_over) %>% ## get estimates for whole numbers
  mutate(hs_educ = high_school_graduate_includes_equivalency + percent_high_school_graduate_or_higher, college_educ = bachelors_degree + percent_bachelors_degree_or_higher, year = 2010) ## add everything together; i have realized that i only need a few vars

education2010 <- education2010 %>% 
  left_join(population) ## join with population

education2010 <- education2010 %>% 
  mutate(hs_pct = (hs_educ/population_total)*100, college_pct = (college_educ/population_total)*100)

education2010 <- education2010 %>% 
  select(state_name, year, hs_educ, hs_pct, college_educ, college_pct)


## 2011 

education2011 <- import("./datasets/education/education2011.csv") ## import 2011

education2011 <- education2011 %>% 
  clean_names() %>% 
  rename(state_name = "label_grouping") ## clean names and rename the ID var

education2011 <- education2011 %>% 
  select(state_name, population_18_to_24_years, high_school_graduate_includes_equivalency, bachelors_degree_or_higher, population_25_years_and_over, high_school_graduate_includes_equivalency_2, bachelors_degree) ## select the vars i want

education2011 <- education2011 %>% 
  mutate(population_18_to_24_years = ifelse(population_18_to_24_years == "", NA, population_18_to_24_years), high_school_graduate_includes_equivalency = ifelse(high_school_graduate_includes_equivalency == "", NA, high_school_graduate_includes_equivalency), bachelors_degree_or_higher = ifelse(bachelors_degree_or_higher == "", NA, bachelors_degree_or_higher), population_25_years_and_over = ifelse(population_25_years_and_over == "", NA, population_25_years_and_over), high_school_graduate_includes_equivalency_2 = ifelse(high_school_graduate_includes_equivalency_2 == "", NA, high_school_graduate_includes_equivalency_2), bachelors_degree = ifelse(bachelors_degree == "", NA, bachelors_degree)) ## replace the empty cells with NAs

education2011 <- education2011 %>% 
  mutate(state_name = str_squish(toupper(state_name))) %>% ## fix the state_name var
  filter(!state_name %in% c("TOTAL", "MALE", "FEMALE", "PUERTO RICO", "DISTRICT OF COLUMBIA")) ## filter out extra rows

education2011 <- education2011 %>% 
  fill(population_18_to_24_years, population_25_years_and_over, high_school_graduate_includes_equivalency, high_school_graduate_includes_equivalency_2, bachelors_degree_or_higher, bachelors_degree, .direction = "up") ## fill upwards

education2011 <- education2011 %>% 
  filter(state_name != "ESTIMATE") ## filter out rows I don't want

education2011 <- education2011 %>% 
  mutate(population_18_to_24_years = as.numeric(gsub(",", "", education2011$population_18_to_24_years)), 
         population_25_years_and_over = as.numeric(gsub(",", "", education2011$population_25_years_and_over)), 
         high_school_graduate_includes_equivalency = as.numeric(gsub("%", "", education2011$high_school_graduate_includes_equivalency))/100, 
         high_school_graduate_includes_equivalency_2 = as.numeric(gsub("%", "", education2011$high_school_graduate_includes_equivalency_2))/100, 
         bachelors_degree_or_higher = as.numeric(gsub("%", "", education2011$bachelors_degree_or_higher))/100, 
  bachelors_degree = as.numeric(gsub("%", "", education2011$bachelors_degree))/100) ## make numeric 

education2011 <- education2011 %>% 
  mutate(hs_18 = population_18_to_24_years*high_school_graduate_includes_equivalency, college_18 = population_18_to_24_years*bachelors_degree_or_higher, hs_25 = population_25_years_and_over*high_school_graduate_includes_equivalency_2, college_25 = population_25_years_and_over*bachelors_degree, hs_educ = hs_18 + hs_25, college_educ = college_18 + college_25, year = 2011) ## get the total number of HS and College grads

education2011 <- education2011 %>% 
  left_join(population) ## join with population

education2011 <- education2011 %>% 
  mutate(hs_pct = (hs_educ/population_total)*100, college_pct = (college_educ/population_total)*100) %>% ## percentage varaibles
  select(state_name, year, hs_educ, hs_pct, college_educ, college_pct) ## select only the one I want

## 2012

education2012 <- import("./datasets/education/education2012.csv") ## import

education2012 <- education2012 %>% 
  clean_names() %>% ## clean names
  rename(state_name = "label_grouping") ## rename

education2012 <- education2012 %>% 
  select(state_name, population_18_to_24_years, high_school_graduate_includes_equivalency, bachelors_degree_or_higher, population_25_years_and_over, high_school_graduate_includes_equivalency_2, bachelors_degree) ## select

education2012 <- education2012 %>% 
  mutate(population_18_to_24_years = ifelse(population_18_to_24_years == "", NA, population_18_to_24_years), high_school_graduate_includes_equivalency = ifelse(high_school_graduate_includes_equivalency == "", NA, high_school_graduate_includes_equivalency), bachelors_degree_or_higher = ifelse(bachelors_degree_or_higher == "", NA, bachelors_degree_or_higher), population_25_years_and_over = ifelse(population_25_years_and_over == "", NA, population_25_years_and_over), high_school_graduate_includes_equivalency_2 = ifelse(high_school_graduate_includes_equivalency_2 == "", NA, high_school_graduate_includes_equivalency_2), bachelors_degree = ifelse(bachelors_degree == "", NA, bachelors_degree)) ## replace the empty cells with NAs

education2012 <- education2012 %>% 
  mutate(state_name = str_squish(toupper(state_name))) %>% ## fix the state_name var
  filter(!state_name %in% c("TOTAL", "MALE", "FEMALE", "PUERTO RICO", "DISTRICT OF COLUMBIA")) ## filter out extra rows

education2012 <- education2012 %>% 
  fill(population_18_to_24_years, population_25_years_and_over, high_school_graduate_includes_equivalency, high_school_graduate_includes_equivalency_2, bachelors_degree_or_higher, bachelors_degree, .direction = "up") ## fill upwards

education2012 <- education2012 %>% 
  filter(state_name != "ESTIMATE") ## filter out extra rows

education2012 <- education2012 %>% 
   mutate(population_18_to_24_years = as.numeric(gsub(",", "", education2012$population_18_to_24_years)), 
         population_25_years_and_over = as.numeric(gsub(",", "", education2012$population_25_years_and_over)), 
         high_school_graduate_includes_equivalency = as.numeric(gsub("%", "", education2012$high_school_graduate_includes_equivalency))/100, 
         high_school_graduate_includes_equivalency_2 = as.numeric(gsub("%", "", education2012$high_school_graduate_includes_equivalency_2))/100, 
         bachelors_degree_or_higher = as.numeric(gsub("%", "", education2012$bachelors_degree_or_higher))/100, 
  bachelors_degree = as.numeric(gsub("%", "", education2012$bachelors_degree))/100) ## make numeric 

education2012 <- education2012 %>% 
  mutate(hs_18 = population_18_to_24_years*high_school_graduate_includes_equivalency, college_18 = population_18_to_24_years*bachelors_degree_or_higher, hs_25 = population_25_years_and_over*high_school_graduate_includes_equivalency_2, college_25 = population_25_years_and_over*bachelors_degree, hs_educ = hs_18 + hs_25, college_educ = college_18 + college_25, year = 2012) ## get the sums

education2012 <- education2012 %>% 
  left_join(population) ## join with population

education2012 <- education2012 %>% 
  mutate(hs_pct = (hs_educ/population_total)*100, college_pct = (college_educ/population_total)*100) %>% ## percentage varaibles
  select(state_name, year, hs_educ, hs_pct, college_educ, college_pct) ## select only the one I want

## 2013

education2013 <- import("./datasets/education/education2013.csv")

education2013 <- education2013 %>% 
  clean_names() %>% ## clean names
  rename(state_name = "label_grouping") ## rename

education2013 <- education2013 %>% 
  select(state_name, population_18_to_24_years, high_school_graduate_includes_equivalency, bachelors_degree_or_higher, population_25_years_and_over, population_25_years_and_over_high_school_graduate_includes_equivalency, population_25_years_and_over_bachelors_degree) ## select

education2013 <- education2013 %>% 
  mutate(population_18_to_24_years = ifelse(population_18_to_24_years == "", NA, population_18_to_24_years), high_school_graduate_includes_equivalency = ifelse(high_school_graduate_includes_equivalency == "", NA, high_school_graduate_includes_equivalency), bachelors_degree_or_higher = ifelse(bachelors_degree_or_higher == "", NA, bachelors_degree_or_higher), population_25_years_and_over = ifelse(population_25_years_and_over == "", NA, population_25_years_and_over), population_25_years_and_over_high_school_graduate_includes_equivalency = ifelse(population_25_years_and_over_high_school_graduate_includes_equivalency == "", NA, population_25_years_and_over_high_school_graduate_includes_equivalency), population_25_years_and_over_bachelors_degree = ifelse(population_25_years_and_over_bachelors_degree == "", NA, population_25_years_and_over_bachelors_degree)) ## replace the empty cells with NAs

education2013 <- education2013 %>% 
  mutate(state_name = str_squish(toupper(state_name))) %>% ## fix the state_name var
  filter(!state_name %in% c("TOTAL", "MALE", "FEMALE", "PUERTO RICO", "DISTRICT OF COLUMBIA")) ## get rid of extra rows

education2013 <- education2013 %>% 
  fill(state_name, population_18_to_24_years, high_school_graduate_includes_equivalency, bachelors_degree_or_higher, population_25_years_and_over, population_25_years_and_over_high_school_graduate_includes_equivalency, population_25_years_and_over_bachelors_degree, .direction = "up") ## fill upwards

education2013 <- education2013 %>% 
  filter(state_name != "ESTIMATE")

education2013 <- education2013 %>% 
  mutate(population_18_to_24_years = as.numeric(gsub(",", "", education2013$population_18_to_24_years)), 
         population_25_years_and_over = as.numeric(gsub(",", "", education2013$population_25_years_and_over)), 
         high_school_graduate_includes_equivalency = as.numeric(gsub("%", "", education2013$high_school_graduate_includes_equivalency))/100, 
         population_25_years_and_over_high_school_graduate_includes_equivalency = as.numeric(gsub("%", "", education2013$population_25_years_and_over_high_school_graduate_includes_equivalency))/100, 
         bachelors_degree_or_higher = as.numeric(gsub("%", "", education2013$bachelors_degree_or_higher))/100, 
  population_25_years_and_over_bachelors_degree = as.numeric(gsub("%", "", education2013$population_25_years_and_over_bachelors_degree))/100) ## make numeric 

education2013 <- education2013 %>% 
   mutate(hs_18 = population_18_to_24_years*high_school_graduate_includes_equivalency, college_18 = population_18_to_24_years*bachelors_degree_or_higher, hs_25 = population_25_years_and_over*population_25_years_and_over_high_school_graduate_includes_equivalency, college_25 = population_25_years_and_over*population_25_years_and_over_bachelors_degree, hs_educ = hs_18 + hs_25, college_educ = college_18 + college_25, year = 2013)

education2013 <- education2013 %>% 
  left_join(population)

education2013 <- education2013 %>% 
  mutate(hs_pct = (hs_educ/population_total)*100, college_pct = (college_educ/population_total)*100) %>% ## percentage varaibles
  select(state_name, year, hs_educ, hs_pct, college_educ, college_pct) ## select only the one I want

## 2014

education2014 <- import("./datasets/education/education2014.csv")

education2014 <- education2014 %>% 
  clean_names() %>% ## clean names
  rename(state_name = "label_grouping") ## rename

education2014 <- education2014 %>% 
  select(state_name, population_18_to_24_years, high_school_graduate_includes_equivalency, bachelors_degree_or_higher, population_25_years_and_over, population_25_years_and_over_high_school_graduate_includes_equivalency, population_25_years_and_over_bachelors_degree) ## select

education2014 <- education2014 %>% 
  mutate(population_18_to_24_years = ifelse(population_18_to_24_years == "", NA, population_18_to_24_years), high_school_graduate_includes_equivalency = ifelse(high_school_graduate_includes_equivalency == "", NA, high_school_graduate_includes_equivalency), bachelors_degree_or_higher = ifelse(bachelors_degree_or_higher == "", NA, bachelors_degree_or_higher), population_25_years_and_over = ifelse(population_25_years_and_over == "", NA, population_25_years_and_over), population_25_years_and_over_high_school_graduate_includes_equivalency = ifelse(population_25_years_and_over_high_school_graduate_includes_equivalency == "", NA, population_25_years_and_over_high_school_graduate_includes_equivalency), population_25_years_and_over_bachelors_degree = ifelse(population_25_years_and_over_bachelors_degree == "", NA, population_25_years_and_over_bachelors_degree)) ## replace the empty cells with NAs

education2014 <- education2014 %>% 
  mutate(state_name = str_squish(toupper(state_name))) %>% ## fix the state_name var
  filter(!state_name %in% c("TOTAL", "MALE", "FEMALE", "PUERTO RICO", "DISTRICT OF COLUMBIA")) ## get rid of extra rows

education2014 <- education2014 %>% 
  fill(state_name, population_18_to_24_years, high_school_graduate_includes_equivalency, bachelors_degree_or_higher, population_25_years_and_over, population_25_years_and_over_high_school_graduate_includes_equivalency, population_25_years_and_over_bachelors_degree, .direction = "up") ## fill upwards

education2014 <- education2014 %>% 
  filter(state_name != "ESTIMATE") ## dump rows

education2014 <- education2014 %>% 
  mutate(population_18_to_24_years = as.numeric(gsub(",", "", education2014$population_18_to_24_years)), 
         population_25_years_and_over = as.numeric(gsub(",", "", education2014$population_25_years_and_over)), 
         high_school_graduate_includes_equivalency = as.numeric(gsub("%", "", education2014$high_school_graduate_includes_equivalency))/100, 
         population_25_years_and_over_high_school_graduate_includes_equivalency = as.numeric(gsub("%", "", education2014$population_25_years_and_over_high_school_graduate_includes_equivalency))/100, 
         bachelors_degree_or_higher = as.numeric(gsub("%", "", education2014$bachelors_degree_or_higher))/100, 
  population_25_years_and_over_bachelors_degree = as.numeric(gsub("%", "", education2014$population_25_years_and_over_bachelors_degree))/100) ## make numeric 

education2014 <- education2014 %>% 
   mutate(hs_18 = population_18_to_24_years*high_school_graduate_includes_equivalency, college_18 = population_18_to_24_years*bachelors_degree_or_higher, hs_25 = population_25_years_and_over*population_25_years_and_over_high_school_graduate_includes_equivalency, college_25 = population_25_years_and_over*population_25_years_and_over_bachelors_degree, hs_educ = hs_18 + hs_25, college_educ = college_18 + college_25, year = 2014)

education2014 <- education2014 %>% 
  left_join(population)

education2014 <- education2014 %>% 
  mutate(hs_pct = (hs_educ/population_total)*100, college_pct = (college_educ/population_total)*100) %>% ## percentage varaibles
  select(state_name, year, hs_educ, hs_pct, college_educ, college_pct) ## select only the one I want


## 2015 

education2015 <- import("./datasets/education/education2015.csv")

education2015 <- education2015 %>% 
  clean_names() %>% ## clean names
  rename(state_name = "label_grouping") ## rename

education2015 <- education2015 %>% 
  select(state_name, population_18_to_24_years, population_18_to_24_years_high_school_graduate_includes_equivalency, population_18_to_24_years_bachelors_degree_or_higher, population_25_years_and_over, population_25_years_and_over_high_school_graduate_includes_equivalency, population_25_years_and_over_bachelors_degree) ## select

education2015 <- education2015 %>% 
  mutate(population_18_to_24_years = ifelse(population_18_to_24_years == "", NA, population_18_to_24_years), 
         population_18_to_24_years_high_school_graduate_includes_equivalency = ifelse(population_18_to_24_years_high_school_graduate_includes_equivalency == "", NA, population_18_to_24_years_high_school_graduate_includes_equivalency), 
         population_18_to_24_years_bachelors_degree_or_higher = ifelse(population_18_to_24_years_bachelors_degree_or_higher == "", NA, population_18_to_24_years_bachelors_degree_or_higher),
         population_25_years_and_over = ifelse(population_25_years_and_over == "", NA, population_25_years_and_over), 
         population_25_years_and_over_high_school_graduate_includes_equivalency = ifelse(population_25_years_and_over_high_school_graduate_includes_equivalency == "", NA, population_25_years_and_over_high_school_graduate_includes_equivalency), 
         population_25_years_and_over_bachelors_degree = ifelse(population_25_years_and_over_bachelors_degree == "", NA, population_25_years_and_over_bachelors_degree)) ## replace the empty cells with NAs

education2015 <- education2015 %>% 
  mutate(state_name = str_squish(toupper(state_name))) %>% ## fix the state_name var
  filter(!state_name %in% c("TOTAL", "MALE", "FEMALE", "PUERTO RICO", "DISTRICT OF COLUMBIA", "MALES", "PERCENT")) ## get rid of extra rows

education2015 <- education2015 %>% 
  fill(state_name, population_18_to_24_years, population_18_to_24_years_high_school_graduate_includes_equivalency, population_18_to_24_years_bachelors_degree_or_higher, population_25_years_and_over, population_25_years_and_over_high_school_graduate_includes_equivalency, population_25_years_and_over_bachelors_degree, .direction = "up") ## fill upwards

education2015 <- education2015 %>% 
  filter(!state_name %in% c("ESTIMATE", "PERCENT MALES", "PERCENT FEMALES", "FEMALES"))## dump rows

education2015 <- education2015 %>% 
  mutate(population_18_to_24_years = as.numeric(gsub(",", "", education2015$population_18_to_24_years)), 
         population_25_years_and_over = as.numeric(gsub(",", "", education2015$population_25_years_and_over)), 
         population_18_to_24_years_high_school_graduate_includes_equivalency = as.numeric(gsub(",", "", education2015$population_18_to_24_years_high_school_graduate_includes_equivalency))/100, 
         population_25_years_and_over_high_school_graduate_includes_equivalency = as.numeric(gsub(",", "", education2015$population_25_years_and_over_high_school_graduate_includes_equivalency))/100, 
         population_18_to_24_years_bachelors_degree_or_higher = as.numeric(gsub(",", "", education2015$population_18_to_24_years_bachelors_degree_or_higher))/100, 
  population_25_years_and_over_bachelors_degree = as.numeric(gsub(",", "", education2015$population_25_years_and_over_bachelors_degree))/100) ## make numeric 

education2015 <- education2015 %>% 
   rename(hs_18 = "population_18_to_24_years_high_school_graduate_includes_equivalency", college_18 = "population_18_to_24_years_bachelors_degree_or_higher", hs_25 = "population_25_years_and_over_high_school_graduate_includes_equivalency", college_25 = "population_25_years_and_over_bachelors_degree") %>% 
  mutate(hs_educ = hs_18 + hs_25, college_educ = college_18 + college_25, year = 2015)

education2015 <- education2015 %>% 
  left_join(population2015) ## join with population total

education2015 <- education2015 %>% 
  mutate(hs_pct = (hs_educ/population_total)*100, college_pct = (college_educ/population_total)*100) %>% ## percentage varaibles
  select(state_name, year, hs_educ, hs_pct, college_educ, college_pct) ## select only the one I want

## 2016

education2016 <- import("./datasets/education/education2016.csv")

education2016 <- education2016 %>% 
  clean_names() %>% ## clean names
  rename(state_name = "label_grouping") ## rename

education2016 <- education2016 %>% 
  select(state_name, population_18_to_24_years, population_18_to_24_years_high_school_graduate_includes_equivalency, population_18_to_24_years_bachelors_degree_or_higher, population_25_years_and_over, population_25_years_and_over_high_school_graduate_includes_equivalency, population_25_years_and_over_bachelors_degree) ## select

education2016 <- education2016 %>% 
  mutate(population_18_to_24_years = ifelse(population_18_to_24_years == "", NA, population_18_to_24_years), 
         population_18_to_24_years_high_school_graduate_includes_equivalency = ifelse(population_18_to_24_years_high_school_graduate_includes_equivalency == "", NA, population_18_to_24_years_high_school_graduate_includes_equivalency), 
         population_18_to_24_years_bachelors_degree_or_higher = ifelse(population_18_to_24_years_bachelors_degree_or_higher == "", NA, population_18_to_24_years_bachelors_degree_or_higher),
         population_25_years_and_over = ifelse(population_25_years_and_over == "", NA, population_25_years_and_over), 
         population_25_years_and_over_high_school_graduate_includes_equivalency = ifelse(population_25_years_and_over_high_school_graduate_includes_equivalency == "", NA, population_25_years_and_over_high_school_graduate_includes_equivalency), 
         population_25_years_and_over_bachelors_degree = ifelse(population_25_years_and_over_bachelors_degree == "", NA, population_25_years_and_over_bachelors_degree)) ## replace the empty cells with NAs

education2016 <- education2016 %>% 
  mutate(state_name = str_squish(toupper(state_name))) %>% ## fix the state_name var
  filter(!state_name %in% c("TOTAL", "MALE", "FEMALE", "PUERTO RICO", "DISTRICT OF COLUMBIA", "MALES", "PERCENT")) ## get rid of extra rows

education2016 <- education2016 %>% 
  fill(state_name, population_18_to_24_years, population_18_to_24_years_high_school_graduate_includes_equivalency, population_18_to_24_years_bachelors_degree_or_higher, population_25_years_and_over, population_25_years_and_over_high_school_graduate_includes_equivalency, population_25_years_and_over_bachelors_degree, .direction = "up") ## fill upwards

education2016 <- education2016 %>% 
  filter(!state_name %in% c("ESTIMATE", "PERCENT MALES", "PERCENT FEMALES", "FEMALES"))## dump rows

education2016 <- education2016 %>% 
  mutate(population_18_to_24_years = as.numeric(gsub(",", "", education2016$population_18_to_24_years)), 
         population_25_years_and_over = as.numeric(gsub(",", "", education2016$population_25_years_and_over)), 
         population_18_to_24_years_high_school_graduate_includes_equivalency = as.numeric(gsub(",", "", education2016$population_18_to_24_years_high_school_graduate_includes_equivalency)), 
         population_25_years_and_over_high_school_graduate_includes_equivalency = as.numeric(gsub(",", "", education2016$population_25_years_and_over_high_school_graduate_includes_equivalency)), 
         population_18_to_24_years_bachelors_degree_or_higher = as.numeric(gsub(",", "", education2016$population_18_to_24_years_bachelors_degree_or_higher)), 
  population_25_years_and_over_bachelors_degree = as.numeric(gsub(",", "", education2016$population_25_years_and_over_bachelors_degree))) ## make numeric 

education2016 <- education2016 %>% 
   rename(hs_18 = "population_18_to_24_years_high_school_graduate_includes_equivalency", college_18 = "population_18_to_24_years_bachelors_degree_or_higher", hs_25 = "population_25_years_and_over_high_school_graduate_includes_equivalency", college_25 = "population_25_years_and_over_bachelors_degree") %>% 
  mutate(hs_educ = hs_18 + hs_25, college_educ = college_18 + college_25, year = 2016)

education2016 <- education2016 %>% 
  left_join(population2016) ## join with population total

education2016 <- education2016 %>% 
  mutate(hs_pct = (hs_educ/population_total)*100, college_pct = (college_educ/population_total)*100) %>% ## percentage varaibles
  select(state_name, year, hs_educ, hs_pct, college_educ, college_pct) ## select only the one I want

## 2017 

education2017 <- import("./datasets/education/education2017.csv")

education2017 <- education2017 %>% 
  clean_names() %>% ## clean names
  rename(state_name = "label_grouping") ## rename

education2017 <- education2017 %>% 
  select(state_name, population_18_to_24_years, population_18_to_24_years_high_school_graduate_includes_equivalency, population_18_to_24_years_bachelors_degree_or_higher, population_25_years_and_over, population_25_years_and_over_high_school_graduate_includes_equivalency, population_25_years_and_over_bachelors_degree) ## select

education2017 <- education2017 %>% 
  mutate(population_18_to_24_years = ifelse(population_18_to_24_years == "", NA, population_18_to_24_years), 
         population_18_to_24_years_high_school_graduate_includes_equivalency = ifelse(population_18_to_24_years_high_school_graduate_includes_equivalency == "", NA, population_18_to_24_years_high_school_graduate_includes_equivalency), 
         population_18_to_24_years_bachelors_degree_or_higher = ifelse(population_18_to_24_years_bachelors_degree_or_higher == "", NA, population_18_to_24_years_bachelors_degree_or_higher),
         population_25_years_and_over = ifelse(population_25_years_and_over == "", NA, population_25_years_and_over), 
         population_25_years_and_over_high_school_graduate_includes_equivalency = ifelse(population_25_years_and_over_high_school_graduate_includes_equivalency == "", NA, population_25_years_and_over_high_school_graduate_includes_equivalency), 
         population_25_years_and_over_bachelors_degree = ifelse(population_25_years_and_over_bachelors_degree == "", NA, population_25_years_and_over_bachelors_degree)) ## replace the empty cells with NAs

education2017 <- education2017 %>% 
  mutate(state_name = str_squish(toupper(state_name))) %>% ## fix the state_name var
  filter(!state_name %in% c("TOTAL", "MALE", "FEMALE", "PUERTO RICO", "DISTRICT OF COLUMBIA", "MALES", "PERCENT")) ## get rid of extra rows

education2017 <- education2017 %>% 
  fill(state_name, population_18_to_24_years, population_18_to_24_years_high_school_graduate_includes_equivalency, population_18_to_24_years_bachelors_degree_or_higher, population_25_years_and_over, population_25_years_and_over_high_school_graduate_includes_equivalency, population_25_years_and_over_bachelors_degree, .direction = "up") ## fill upwards

education2017 <- education2017 %>% 
  filter(!state_name %in% c("ESTIMATE", "PERCENT MALE", "PERCENT FEMALE", "FEMALES"))## dump rows

education2017 <- education2017 %>% 
  mutate(population_18_to_24_years = as.numeric(gsub(",", "", education2017$population_18_to_24_years)), 
         population_25_years_and_over = as.numeric(gsub(",", "", education2017$population_25_years_and_over)), 
         population_18_to_24_years_high_school_graduate_includes_equivalency = as.numeric(gsub(",", "", education2017$population_18_to_24_years_high_school_graduate_includes_equivalency)), 
         population_25_years_and_over_high_school_graduate_includes_equivalency = as.numeric(gsub(",", "", education2017$population_25_years_and_over_high_school_graduate_includes_equivalency)), 
         population_18_to_24_years_bachelors_degree_or_higher = as.numeric(gsub(",", "", education2017$population_18_to_24_years_bachelors_degree_or_higher)), 
  population_25_years_and_over_bachelors_degree = as.numeric(gsub(",", "", education2017$population_25_years_and_over_bachelors_degree))) ## make numeric 

education2017 <- education2017 %>% 
   rename(hs_18 = "population_18_to_24_years_high_school_graduate_includes_equivalency", college_18 = "population_18_to_24_years_bachelors_degree_or_higher", hs_25 = "population_25_years_and_over_high_school_graduate_includes_equivalency", college_25 = "population_25_years_and_over_bachelors_degree") %>% 
  mutate(hs_educ = hs_18 + hs_25, college_educ = college_18 + college_25, year = 2017)

education2017 <- education2017 %>% 
  left_join(population2017) ## join with population total

education2017 <- education2017 %>% 
  mutate(hs_pct = (hs_educ/population_total)*100, college_pct = (college_educ/population_total)*100) %>% ## percentage varaibles
  select(state_name, year, hs_educ, hs_pct, college_educ, college_pct) ## select only the one I want

## 2018
education2018 <- import("./datasets/education/education2018.csv")

education2018 <- education2018 %>% 
  clean_names() %>% ## clean names
  rename(state_name = "label_grouping") ## rename

education2018 <- education2018 %>% 
  select(state_name, 
         age_by_educational_attainment_population_18_to_24_years, 
         age_by_educational_attainment_population_18_to_24_years_high_school_graduate_includes_equivalency, 
         age_by_educational_attainment_population_18_to_24_years_bachelors_degree_or_higher, 
         age_by_educational_attainment_population_25_years_and_over, 
         age_by_educational_attainment_population_25_years_and_over_high_school_graduate_includes_equivalency, 
         age_by_educational_attainment_population_25_years_and_over_bachelors_degree) ## select

education2018 <- education2018 %>% 
  rename(population_18_to_24_years = "age_by_educational_attainment_population_18_to_24_years", 
         population_18_to_24_years_high_school_graduate_includes_equivalency = "age_by_educational_attainment_population_18_to_24_years_high_school_graduate_includes_equivalency", 
         population_18_to_24_years_bachelors_degree_or_higher = "age_by_educational_attainment_population_18_to_24_years_bachelors_degree_or_higher", 
         population_25_years_and_over = "age_by_educational_attainment_population_25_years_and_over", 
         population_25_years_and_over_high_school_graduate_includes_equivalency = "age_by_educational_attainment_population_25_years_and_over_high_school_graduate_includes_equivalency", 
         population_25_years_and_over_bachelors_degree = "age_by_educational_attainment_population_25_years_and_over_bachelors_degree") ## rename (ugh)

education2018 <- education2018 %>% 
  mutate(population_18_to_24_years = ifelse(population_18_to_24_years == "", NA, population_18_to_24_years), 
         population_18_to_24_years_high_school_graduate_includes_equivalency = ifelse(population_18_to_24_years_high_school_graduate_includes_equivalency == "", NA, population_18_to_24_years_high_school_graduate_includes_equivalency), 
         population_18_to_24_years_bachelors_degree_or_higher = ifelse(population_18_to_24_years_bachelors_degree_or_higher == "", NA, population_18_to_24_years_bachelors_degree_or_higher),
         population_25_years_and_over = ifelse(population_25_years_and_over == "", NA, population_25_years_and_over), 
         population_25_years_and_over_high_school_graduate_includes_equivalency = ifelse(population_25_years_and_over_high_school_graduate_includes_equivalency == "", NA, population_25_years_and_over_high_school_graduate_includes_equivalency), 
         population_25_years_and_over_bachelors_degree = ifelse(population_25_years_and_over_bachelors_degree == "", NA, population_25_years_and_over_bachelors_degree)) ## replace the empty cells with NAs

education2018 <- education2018 %>% 
  mutate(state_name = str_squish(toupper(state_name))) %>% ## fix the state_name var
  filter(!state_name %in% c("TOTAL", "MALE", "FEMALE", "PUERTO RICO", "DISTRICT OF COLUMBIA", "MALES", "PERCENT")) ## get rid of extra rows

education2018 <- education2018 %>% 
  fill(state_name, population_18_to_24_years, population_18_to_24_years_high_school_graduate_includes_equivalency, population_18_to_24_years_bachelors_degree_or_higher, population_25_years_and_over, population_25_years_and_over_high_school_graduate_includes_equivalency, population_25_years_and_over_bachelors_degree, .direction = "up") ## fill upwards

education2018 <- education2018 %>% 
  filter(!state_name %in% c("ESTIMATE", "PERCENT MALE", "PERCENT FEMALE", "FEMALES"))## dump rows

education2018 <- education2018 %>% 
  mutate(population_18_to_24_years = as.numeric(gsub(",", "", education2018$population_18_to_24_years)), 
         population_25_years_and_over = as.numeric(gsub(",", "", education2018$population_25_years_and_over)), 
         population_18_to_24_years_high_school_graduate_includes_equivalency = as.numeric(gsub(",", "", education2018$population_18_to_24_years_high_school_graduate_includes_equivalency)), 
         population_25_years_and_over_high_school_graduate_includes_equivalency = as.numeric(gsub(",", "", education2018$population_25_years_and_over_high_school_graduate_includes_equivalency)), 
         population_18_to_24_years_bachelors_degree_or_higher = as.numeric(gsub(",", "", education2018$population_18_to_24_years_bachelors_degree_or_higher)), 
  population_25_years_and_over_bachelors_degree = as.numeric(gsub(",", "", education2018$population_25_years_and_over_bachelors_degree))) ## make numeric 

education2018 <- education2018 %>% 
   rename(hs_18 = "population_18_to_24_years_high_school_graduate_includes_equivalency", college_18 = "population_18_to_24_years_bachelors_degree_or_higher", hs_25 = "population_25_years_and_over_high_school_graduate_includes_equivalency", college_25 = "population_25_years_and_over_bachelors_degree") %>% 
  mutate(hs_educ = hs_18 + hs_25, college_educ = college_18 + college_25, year = 2018)

education2018 <- education2018 %>% 
  left_join(population2018) ## join with population total

education2018 <- education2018 %>% 
  mutate(hs_pct = (hs_educ/population_total)*100, college_pct = (college_educ/population_total)*100) %>% ## percentage varaibles
  select(state_name, year, hs_educ, hs_pct, college_educ, college_pct) ## select only the one I want

## 2019

education2019 <- import("./datasets/education/education2019.csv")

education2019 <- education2019 %>% 
  clean_names() %>% ## clean names
  rename(state_name = "label_grouping") ## rename

education2019 <- education2019 %>% 
  select(state_name, 
         age_by_educational_attainment_population_18_to_24_years, 
         age_by_educational_attainment_population_18_to_24_years_high_school_graduate_includes_equivalency, 
         age_by_educational_attainment_population_18_to_24_years_bachelors_degree_or_higher, 
         age_by_educational_attainment_population_25_years_and_over, 
         age_by_educational_attainment_population_25_years_and_over_high_school_graduate_includes_equivalency, 
         age_by_educational_attainment_population_25_years_and_over_bachelors_degree) ## select

education2019 <- education2019 %>% 
  rename(population_18_to_24_years = "age_by_educational_attainment_population_18_to_24_years", 
         population_18_to_24_years_high_school_graduate_includes_equivalency = "age_by_educational_attainment_population_18_to_24_years_high_school_graduate_includes_equivalency", 
         population_18_to_24_years_bachelors_degree_or_higher = "age_by_educational_attainment_population_18_to_24_years_bachelors_degree_or_higher", 
         population_25_years_and_over = "age_by_educational_attainment_population_25_years_and_over", 
         population_25_years_and_over_high_school_graduate_includes_equivalency = "age_by_educational_attainment_population_25_years_and_over_high_school_graduate_includes_equivalency", 
         population_25_years_and_over_bachelors_degree = "age_by_educational_attainment_population_25_years_and_over_bachelors_degree") ## rename (ugh)

education2019 <- education2019 %>% 
  mutate(population_18_to_24_years = ifelse(population_18_to_24_years == "", NA, population_18_to_24_years), 
         population_18_to_24_years_high_school_graduate_includes_equivalency = ifelse(population_18_to_24_years_high_school_graduate_includes_equivalency == "", NA, population_18_to_24_years_high_school_graduate_includes_equivalency), 
         population_18_to_24_years_bachelors_degree_or_higher = ifelse(population_18_to_24_years_bachelors_degree_or_higher == "", NA, population_18_to_24_years_bachelors_degree_or_higher),
         population_25_years_and_over = ifelse(population_25_years_and_over == "", NA, population_25_years_and_over), 
         population_25_years_and_over_high_school_graduate_includes_equivalency = ifelse(population_25_years_and_over_high_school_graduate_includes_equivalency == "", NA, population_25_years_and_over_high_school_graduate_includes_equivalency), 
         population_25_years_and_over_bachelors_degree = ifelse(population_25_years_and_over_bachelors_degree == "", NA, population_25_years_and_over_bachelors_degree)) ## replace the empty cells with NAs

education2019 <- education2019 %>% 
  mutate(state_name = str_squish(toupper(state_name))) %>% ## fix the state_name var
  filter(!state_name %in% c("TOTAL", "MALE", "FEMALE", "PUERTO RICO", "DISTRICT OF COLUMBIA", "MALES", "PERCENT")) ## get rid of extra rows

education2019 <- education2019 %>% 
  fill(state_name, population_18_to_24_years, population_18_to_24_years_high_school_graduate_includes_equivalency, population_18_to_24_years_bachelors_degree_or_higher, population_25_years_and_over, population_25_years_and_over_high_school_graduate_includes_equivalency, population_25_years_and_over_bachelors_degree, .direction = "up") ## fill upwards

education2019 <- education2019 %>% 
  filter(!state_name %in% c("ESTIMATE", "PERCENT MALE", "PERCENT FEMALE", "FEMALES"))## dump rows

education2019 <- education2019 %>% 
  mutate(population_18_to_24_years = as.numeric(gsub(",", "", education2019$population_18_to_24_years)), 
         population_25_years_and_over = as.numeric(gsub(",", "", education2019$population_25_years_and_over)), 
         population_18_to_24_years_high_school_graduate_includes_equivalency = as.numeric(gsub(",", "", education2019$population_18_to_24_years_high_school_graduate_includes_equivalency)), 
         population_25_years_and_over_high_school_graduate_includes_equivalency = as.numeric(gsub(",", "", education2019$population_25_years_and_over_high_school_graduate_includes_equivalency)), 
         population_18_to_24_years_bachelors_degree_or_higher = as.numeric(gsub(",", "", education2019$population_18_to_24_years_bachelors_degree_or_higher)), 
  population_25_years_and_over_bachelors_degree = as.numeric(gsub(",", "", education2019$population_25_years_and_over_bachelors_degree))) ## make numeric 

education2019 <- education2019 %>% 
   rename(hs_18 = "population_18_to_24_years_high_school_graduate_includes_equivalency", college_18 = "population_18_to_24_years_bachelors_degree_or_higher", hs_25 = "population_25_years_and_over_high_school_graduate_includes_equivalency", college_25 = "population_25_years_and_over_bachelors_degree") %>% 
  mutate(hs_educ = hs_18 + hs_25, college_educ = college_18 + college_25, year = 2019)

education2019 <- education2019 %>% 
  left_join(population2019) ## join with population total

education2019 <- education2019 %>% 
  mutate(hs_pct = (hs_educ/population_total)*100, college_pct = (college_educ/population_total)*100) %>% ## percentage varaibles
  select(state_name, year, hs_educ, hs_pct, college_educ, college_pct) ## select only the one I want

## 2021

education2021 <- import("./datasets/education/education2021.csv")

education2021 <- education2021 %>% 
  clean_names() %>% ## clean names
  rename(state_name = "label_grouping") ## rename

education2021 <- education2021 %>% 
  select(state_name, 
         age_by_educational_attainment_population_18_to_24_years, 
         age_by_educational_attainment_population_18_to_24_years_high_school_graduate_includes_equivalency, 
         age_by_educational_attainment_population_18_to_24_years_bachelors_degree_or_higher, 
         age_by_educational_attainment_population_25_years_and_over, 
         age_by_educational_attainment_population_25_years_and_over_high_school_graduate_includes_equivalency, 
         age_by_educational_attainment_population_25_years_and_over_bachelors_degree) ## select

education2021 <- education2021 %>% 
  rename(population_18_to_24_years = "age_by_educational_attainment_population_18_to_24_years", 
         population_18_to_24_years_high_school_graduate_includes_equivalency = "age_by_educational_attainment_population_18_to_24_years_high_school_graduate_includes_equivalency", 
         population_18_to_24_years_bachelors_degree_or_higher = "age_by_educational_attainment_population_18_to_24_years_bachelors_degree_or_higher", 
         population_25_years_and_over = "age_by_educational_attainment_population_25_years_and_over", 
         population_25_years_and_over_high_school_graduate_includes_equivalency = "age_by_educational_attainment_population_25_years_and_over_high_school_graduate_includes_equivalency", 
         population_25_years_and_over_bachelors_degree = "age_by_educational_attainment_population_25_years_and_over_bachelors_degree") ## rename (ugh)

education2021 <- education2021 %>% 
  mutate(population_18_to_24_years = ifelse(population_18_to_24_years == "", NA, population_18_to_24_years), 
         population_18_to_24_years_high_school_graduate_includes_equivalency = ifelse(population_18_to_24_years_high_school_graduate_includes_equivalency == "", NA, population_18_to_24_years_high_school_graduate_includes_equivalency), 
         population_18_to_24_years_bachelors_degree_or_higher = ifelse(population_18_to_24_years_bachelors_degree_or_higher == "", NA, population_18_to_24_years_bachelors_degree_or_higher),
         population_25_years_and_over = ifelse(population_25_years_and_over == "", NA, population_25_years_and_over), 
         population_25_years_and_over_high_school_graduate_includes_equivalency = ifelse(population_25_years_and_over_high_school_graduate_includes_equivalency == "", NA, population_25_years_and_over_high_school_graduate_includes_equivalency), 
         population_25_years_and_over_bachelors_degree = ifelse(population_25_years_and_over_bachelors_degree == "", NA, population_25_years_and_over_bachelors_degree)) ## replace the empty cells with NAs

education2021 <- education2021 %>% 
  mutate(state_name = str_squish(toupper(state_name))) %>% ## fix the state_name var
  filter(!state_name %in% c("TOTAL", "MALE", "FEMALE", "PUERTO RICO", "DISTRICT OF COLUMBIA", "MALES", "PERCENT")) ## get rid of extra rows

education2021 <- education2021 %>% 
  fill(state_name, population_18_to_24_years, population_18_to_24_years_high_school_graduate_includes_equivalency, population_18_to_24_years_bachelors_degree_or_higher, population_25_years_and_over, population_25_years_and_over_high_school_graduate_includes_equivalency, population_25_years_and_over_bachelors_degree, .direction = "up") ## fill upwards

education2021 <- education2021 %>% 
  filter(!state_name %in% c("ESTIMATE", "PERCENT MALE", "PERCENT FEMALE", "FEMALES"))## dump rows

education2021 <- education2021 %>% 
  mutate(population_18_to_24_years = as.numeric(gsub(",", "", education2021$population_18_to_24_years)), 
         population_25_years_and_over = as.numeric(gsub(",", "", education2021$population_25_years_and_over)), 
         population_18_to_24_years_high_school_graduate_includes_equivalency = as.numeric(gsub(",", "", education2021$population_18_to_24_years_high_school_graduate_includes_equivalency)), 
         population_25_years_and_over_high_school_graduate_includes_equivalency = as.numeric(gsub(",", "", education2021$population_25_years_and_over_high_school_graduate_includes_equivalency)), 
         population_18_to_24_years_bachelors_degree_or_higher = as.numeric(gsub(",", "", education2021$population_18_to_24_years_bachelors_degree_or_higher)), 
  population_25_years_and_over_bachelors_degree = as.numeric(gsub(",", "", education2021$population_25_years_and_over_bachelors_degree))) ## make numeric 

education2021 <- education2021 %>% 
   rename(hs_18 = "population_18_to_24_years_high_school_graduate_includes_equivalency", college_18 = "population_18_to_24_years_bachelors_degree_or_higher", hs_25 = "population_25_years_and_over_high_school_graduate_includes_equivalency", college_25 = "population_25_years_and_over_bachelors_degree") %>% 
  mutate(hs_educ = hs_18 + hs_25, college_educ = college_18 + college_25, year = 2021)

education2021 <- education2021 %>% 
  left_join(population2021) ## join with population total

education2021 <- education2021 %>% 
  mutate(hs_pct = (hs_educ/population_total)*100, college_pct = (college_educ/population_total)*100) %>% ## percentage varaibles
  select(state_name, year, hs_educ, hs_pct, college_educ, college_pct) ## select only the one I want


education1021 <- education2010 %>% 
  full_join(education2011) %>% 
  full_join(education2012) %>% 
  full_join(education2013) %>% 
  full_join(education2014) %>% 
  full_join(education2015) %>% 
  full_join(education2016) %>% 
  full_join(education2017) %>% 
  full_join(education2018) %>% 
  full_join(education2019) %>% 
  full_join(education2012) ## join everything together

ecuation1021 <- education1021 %>% 
  mutate(hs_pct = hs_pct/100, college_pct = college_pct/100) ## convert to decimals

##export(education1021, "education1021.csv") ## export
```

```{r}
## let's join it all together

education <- import("./datasets/education1021.csv") ## educational attainmnet
population_dems <- import("./datasets/population_demographics8720.csv") ## population demographics
pollib <- import("./datasets/pollib_median8720.csv") ## policy liberalism
initiatives <- import("./datasets/initiatives2023.csv") ## initiatives
evangelical <- import("./datasets/evangelical2021_2011.csv") ## evangelical population
income <- import("./datasets/incomepcap2011_2022.csv") ## income per capita
population <- population_all ## population
unified <- import("./datasets/unified_data.csv") ## state unity
crosswalk <- import("./datasets/state_codes.csv") ## crosswalk file
bowen <- import("./datasets/bowen8720.csv") ## bowen standardsa

evangelical <- evangelical %>% 
  select(-c(pew_bornagain, weight, total, num)) ## drop some unnecessary vars

unified <- unified %>% 
  mutate(state_name = str_squish(toupper(state_name))) ## fix state name case

bowen <- bowen %>% 
  mutate(state_name = str_squish(toupper(state_name))) ## fix state name case

population_dems <- population_dems %>% 
  select(-state_no)

covars <- population_all %>%  
  full_join(population_dems) %>% 
  full_join(evangelical) %>% 
  full_join(pollib) %>% 
  full_join(income) %>% 
  full_join(initiatives) %>% 
  full_join(unified) %>% 
  full_join(bowen) %>% 
  full_join(education) %>% 
  left_join(crosswalk)## join everything together (not working )

covars <- covars %>% 
  filter(year >= 1987) ## drop years


#covars <- covars %>% 
  #left_join(risk_set) ## join wiht existing risk set

# covars <- covars %>% 
  #select(-c(direction, category, statename, policy, adoption_year)) ## drop some vars

## this isn't quite right but I gotta spend some time on it
```

```{r}
## check new coverage

check_pop <- covars %>% 
  select(state_name, state, year, population_total) %>% 
  group_by(state_name) %>% 
  summarize(min(year), max(year), n())

check_female <- covars %>% 
  select(state_name, state, year, female_pop) %>% 
  group_by(state_name) %>% 
  summarize(min(year), max(year))

check_init <- covars %>% 
  select(state_name, state, year, std_init_use) %>% 
  group_by(state_name) %>% 
  summarize(min(year), max(year))

check_unified <- covars %>% 
  select(state_name, state, year, party_control) %>% 
  group_by(state_name) %>% 
  summarize(min(year), max(year))
```

```{r}
## working out the problem with why there are too many rows in my dataset

## ok, let's join together all the evangelical data
evangelical <- evangelical %>% 
  mutate(year = as.numeric(year)) ## get the year var to be the exact same

evangelical <- evangelical %>% 
  left_join(crosswalk) ## join with crosswalk file

evangelical1 <- evangelical1 %>% 
  left_join(crosswalk) ## join the crosswalk file, getting all of the ID vars

evangelical2 <- evangelical %>% 
  full_join(evangelical1) ## join together, for 1800 rows

evangelical2 <- evangelical2 %>% 
  select(-c(stateno))

evangelical2 <- evangelical2 %>% 
  mutate(state_icpsr = as.numeric(state_icpsr))

income1 <- state_data %>% 
  full_join(expanded_years) %>% 
  full_join(race_health) %>% 
  full_join(crosswalk) ## get all the earlier rows of the income vars together

income1 <- income1 %>% 
  select(state_name, state, statefip, state_icpsr, stateno, year, incomepcap) ## select only the ID vars and incomepcap

income1 <- income1 %>% 
  filter(year >= 1987) ## dump extra years

income1 <- income1 %>% 
  filter(!is.na(statefip)) %>% 
  filter(!is.na(incomepcap)) ## get rid of  the extra rows

income1 <- income1 %>% 
  distinct() ## get rid of extra rows

income1 <- income1 %>% 
  full_join(income) ## join with the new data, 1800 rows

## population dems

existing <- state_data %>% 
  full_join(expanded_years) %>% 
  full_join(race_health) %>% 
  full_join(crosswalk) ## existing covars dataset (the old stuff)

pop_dems1 <- existing %>% 
  select(state_name, state, statefip, state_icpsr, stateno, year, pct_black, pctblack) ## select the existing popuulation vars

pop_dems1 <- pop_dems1 %>% 
  filter(!is.na(statefip)) # get rid of NAs

pop_dems1 <- pop_dems1 %>% 
  filter(!is.na(pct_black)) ## get rid of NAs

pop_dems1 <- pop_dems1 %>% 
  filter(year >= 1987) ## get rid of early years I don't want

population_dems <- population_dems %>% 
  filter(!state %in% c("GU", "VI", "DC", "PR")) ## get rid of extra states

population_dems <- population_dems %>% 
  distinct(state_name, state, year, .keep_all = TRUE) ## make distince

population_dems <- population_dems %>% 
  full_join(pop_dems1) %>% 
  distinct(state_name, state, year, .keep_all = TRUE) ## i think this is the best i can do for this one

population_dems <- population_dems %>% 
  select(-population_total) ## drop extra population var

## initiatives

initiatives <- initiatives %>% 
  filter(year >= 1987) %>% 
  distinct(state_name, state, year, .keep_all = TRUE) ## distinct and filter years to get 1800 rows

## unified

unified1 <- existing %>% 
  select(state_name, state, year, statefip, state_icpsr, unified) ## get the existing risk set data but only the vars I need

unified1 <- unified1 %>% 
  filter(year >= 1987 & year < 2015) %>% ## filter the years I don't want in this df
  distinct(state_name, state, year, .keep_all = T) ## rid this object of duplicate rows
 
unified <- unified %>% 
  full_join(unified1) ## she complete

## population

population_all <- population_all %>% 
  left_join(crosswalk) ## join wiht crosswalk file

population_all <- population_all %>% 
  select(-stateno) ## drop state number (cause ew)

population_all <- population_all %>% 
  filter(!state %in% c("DC", "GU", "PR", "VI")) ## drop extra non-states
  

pop_check2 <- population_all %>% 
  group_by(state_name) %>% 
  summarize(n(), min(year), max(year)) ## readyyy
```

```{r}
## let's do the final join

covariates <- population_all %>% 
  full_join(population_dems) %>%  ## 1850 obervations (good)
  select(-statefip)

covariates <- covariates %>% 
  left_join(income1) ## join with income 1850 observations (correct) (left join to drop the fips var)

covariates <- covariates %>% 
  full_join(education) ## join with education, 1850 observations (correct)

covariates <- covariates %>% 
  left_join(pollib) ## ## join with income 1850 observations (correct) (left join to drop the fips var)

covariates <- covariates %>% 
  left_join(bowen) ## join with bowen standards

covariates <- covariates %>% 
  left_join(unified) ## join with unified, 1850 observations

covariates <- covariates %>% 
  left_join(initiatives) %>% 
  select(-c(mean, sd)) ## join with initiatives, 1850 observations (stay winning)

covariates <- covariates %>% 
  left_join(evangelical2) ## join with evangelical, 1850 observations (slaying)

covariates <- covariates %>% 
  left_join(crosswalk) ## join the crosswalk dataset to fill in the missing values of the fips codes and stuff 

covariates <- covariates %>% 
  select(-c(stateno, statefip, state_num)) ## get rid of redundant columns that i shall not need 
  
## export(covariates, "covariates.csv") ## export this
```

