---
title: "Nondiscrimination_Risk_Set"
author: "Grace Rade"
date: "2023-01-10"
output: html_document
---
```{r}
library(tidyverse)
library(rio)
require(lme4)

empty_data <- read.csv("datasets/EmptyData2.csv")


nondiscrimination_data <- read.csv("datasets/Laws_Policies.csv") %>% 
  filter(Category == "Nondiscrimination", Policy == "1") %>% 
  select(-c(Description, X, Month, Day, Date, Policy)) %>% 
  mutate(Adoption_Year = Year) %>% 
  select(-Year)


nondiscrimination_risk_set <- empty_data %>% 
  left_join(nondiscrimination_data)%>% 
  mutate(Policy= if_else(Adoption_Year == Year, 1, 0)) %>%
  mutate(Adoption_Year = replace_na(Adoption_Year, 2022)) %>%
  filter(Adoption_Year>=Year) %>%
  mutate(adoption=ifelse(Year==Adoption_Year & Policy==1, 1, 0))

nondiscrimination_risk_set$Policy[is.na(nondiscrimination_risk_set$Policy)] <- 0
nondiscrimination_risk_set$Category[is.na(nondiscrimination_risk_set$Category)] <- "Nondiscrimination"
```

```{r}
export(nondiscrimination_risk_set, "nondicrimination_risk_set.csv")
```

