---
title: "Risk_States.Rmd"
author: "Grace Rade"
date: "2023-01-30"
output: html_document
---
```{r}
library(tidyverse)
library(rio)
library(haven)
library(janitor)

all_risk_set <- read.csv("datasets/all_risk_set.csv") %>% 
  clean_names()

state_data <- read_csv("datasets/risk_states1.csv")

evang <- read.csv("datasets/evangelical_pop data.csv") %>% 
  select(year, state, evangelical_pop, st) %>% 
  filter(!is.na(evangelical_pop))


evang2 <- import("datasets/ces_data.dta") %>% 
  rename(evangelical_pop = "pew_bornagain", state = 'state_name', st = "state") %>% 
  select(year, state, evangelical_pop, st) %>% 
  mutate(evangelical_pop = evangelical_pop*100)

evang2$state <- str_to_title(evang2$state)

evang <- evang %>% 
  full_join(evang2)

risk_state <- all_risk_set %>% 
  full_join(state_data) %>% 
  mutate(duration = year - first_year, duration_sq = duration^2, duration_cub = duration^3) %>% 
  mutate(lawrence = ifelse(lag(adoption_year) <= 2003, 0, 1), obergefell = ifelse(lag(adoption_year) <= 2015, 0, 1))

risk_state <- risk_state %>% 
  left_join(evang) %>% 
  select(state, year, policy, category, direction, adoption_year, population_total, pollib_median, incomepcap, income, std_bowen1, std_bowen2, unified, duration, duration_sq, duration_cub, nbrs_lag, nbrs, lawrence, obergefell, std_init_use, evangelical_pop) 



nums <- risk_state %>% 
  filter(!is.na(evangelical_pop)) %>% 
  group_by(year) %>% 
  summarize(n())

```

```{r}
export(risk_state, "risk_states3.csv")
```

