---
title: "Modeling5"
author: "Grace Rade"
date: "2023-03-10"
output: html_document
---
```{r}
library(tidyverse)
library(rio)
library(haven)
library(stargazer)
library(reader)

state_data <- import("./datasets/risk_states3.csv")
```

```{r}
## making new data for predicted prob, primary model total
constants <- state_data %>% 
  na.omit() %>% 
  summarize(pop_med = median(population_total), pollib_med = median(pollib_median), income_med = median(incomepcap), bowen1_med = median(std_bowen1), bowen2_med = median(std_bowen2), duration_med = median(duration), duration_sq_med = median(duration_sq), duration_cub_med = median(duration_cub), init_med = median(std_init_use), evang_med = median(evangelical_pop))
```

```{r}
primary <-  glm(policy~lawrence + obergefell + nbrs_lag + population_total + pollib_median + incomepcap  + unified + std_bowen1 + std_bowen2 + duration + duration_sq + duration_cub + std_init_use, data = state_data, family = binomial)

summary(primary)

## lawrence = 0, obergefell = 0
primary_total <- with(state_data, data.frame(pollib_median=0.330086, population_total=
3591363, incomepcap = 30056, std_bowen1 = -0.1149914, std_bowen2 = 0.1547105, duration = 8, duration_sq = 64, duration_cub = 512, std_init_use = -0.4535984, unified = 1, nbrs_lag=seq(0, 3, by = 1), lawrence = 0, obergefell = 0)) 

pred <- as.data.frame(predict(primary, primary_total, type="response", se.fit=TRUE)) 

primary_total$pred_prob <- pred$fit
primary_total$pred_lower <- pred$fit-(1.96*pred$se.fit)
primary_total$pred_upper <- pred$fit+(1.96*pred$se.fit)

primary_total$lawrence <- as.factor(primary_total$lawrence)
primary_total$obergefell <- as.factor(primary_total$obergefell)

ggplot(primary_total, aes(x=as.factor(lawrence), y=pred_prob))+
geom_ribbon(aes(ymin = pred_lower, ymax = pred_upper),fill = "grey70")+
  geom_point() +
  geom_errorbar(aes(ymin = pred_lower, ymax = pred_upper))## just playing around here with the variable


## lawrence = 1, obergefell = 0
primary_total1 <- with(state_data, data.frame(pollib_median=0.330086, population_total= 3591363, incomepcap = 30056, std_bowen1 = -0.1149914, std_bowen2 = 0.1547105, duration = 8, duration_sq = 64, duration_cub = 512, std_init_use = -0.4535984, unified = 1, nbrs_lag=seq(0, 3, by = 1), lawrence = 1, obergefell = 0)) ## change nrbs_lag later

pred1 <- as.data.frame(predict(primary, primary_total1, type="response", se.fit=TRUE)) ## won't work becuase of category... took it out becuase i am impatient

primary_total1$pred_prob <- pred1$fit
primary_total1$pred_lower <- pred1$fit-(1.96*pred$se.fit)
primary_total1$pred_upper <- pred1$fit+(1.96*pred$se.fit)

primary_total1$lawrence <- as.factor(primary_total1$lawrence)
primary_total1$obergefell <- as.factor(primary_total1$obergefell)


## lawrence = 1, obergefell = 1
primary_total2 <- with(state_data, data.frame(pollib_median=0.330086, population_total=
3591363, incomepcap = 30056, std_bowen1 = -0.1149914, std_bowen2 = 0.1547105, duration = 8, duration_sq = 64, duration_cub = 512, std_init_use = -0.4535984, unified = 1, nbrs_lag=seq(0, 3, by = 1), lawrence = 1, obergefell = 1)) 

pred2 <- as.data.frame(predict(primary, primary_total2, type="response", se.fit=TRUE)) ## won't work becuase of category... took it out becuase i am impatient

primary_total2$pred_prob <- pred2$fit
primary_total2$pred_lower <- pred2$fit-(1.96*pred$se.fit)
primary_total2$pred_upper <- pred2$fit+(1.96*pred$se.fit)

primary_total2$lawrence <- as.factor(primary_total2$lawrence)
primary_total2$obergefell <- as.factor(primary_total2$obergefell)

## secondary model total

secondary_interact <- glm(policy~lawrence*evangelical_pop+ obergefell + nbrs_lag + population_total + pollib_median + incomepcap + unified + std_bowen1 + std_bowen2 + duration + duration_sq + duration_cub + std_init_use, data = state_data, family = binomial)

summary(secondary_interact)


## lawrence = 0, obergefell = 0
secondary_total <- with(state_data, data.frame(pollib_median=0.330086, population_total = 3591363, incomepcap = 30056, std_bowen1 = -0.1149914, std_bowen2 = 0.1547105, duration = 8, duration_sq = 64, duration_cub = 512, std_init_use = -0.4535984, unified = 1, nbrs_lag=seq(0, 3, by = 1), lawrence = 0, obergefell = 0, evangelical_pop = seq(0,50, by=15)))

pred3 <- as.data.frame(predict(secondary_interact, secondary_total, type="response", se.fit=TRUE))

secondary_total$pred_prob <- pred3$fit
secondary_total$pred_lower <- pred3$fit-(1.96*pred$se.fit)
secondary_total$pred_upper <- pred3$fit+(1.96*pred$se.fit)

secondary_total$lawrence <- as.factor(secondary_total$lawrence)
secondary_total$obergefell <- as.factor(secondary_total$obergefell)

ggplot(secondary_total, aes(x = evangelical_pop, y = pred_prob, color = lawrence)) + geom_smooth(method = "lm")



## lawrence = 1, obergefell = 0
secondary_total1 <- with(state_data, data.frame(pollib_median=0.330086, population_total = 3591363, incomepcap = 30056, std_bowen1 = -0.1149914, std_bowen2 = 0.1547105, duration = 8, duration_sq = 64, duration_cub = 512, std_init_use = -0.4535984, unified = 1, nbrs_lag=seq(0, 3, by = 1), lawrence = 1, obergefell = 0, evangelical_pop = seq(0,50, by=15)))

pred4 <- as.data.frame(predict(secondary_interact, secondary_total1, type="response", se.fit=TRUE))

secondary_total1$pred_prob <- pred4$fit
secondary_total1$pred_lower <- pred4$fit-(1.96*pred$se.fit)
secondary_total1$pred_upper <- pred4$fit+(1.96*pred$se.fit)

secondary_total1$lawrence <- as.factor(secondary_total1$lawrence)
secondary_total1$obergefell <- as.factor(secondary_total1$obergefell)

ggplot(secondary_total1, aes(x = evangelical_pop, y = pred_prob, color = lawrence)) + geom_smooth(method = "lm")


## lawrence = 1, obergefell = 1
secondary_total2 <- with(state_data, data.frame(pollib_median=0.330086, population_total = 3591363, incomepcap = 30056, std_bowen1 = -0.1149914, std_bowen2 = 0.1547105, duration = 8, duration_sq = 64, duration_cub = 512, std_init_use = -0.4535984, unified = 1, nbrs_lag=seq(0, 3, by = 1), lawrence = 1, obergefell = 1, evangelical_pop = seq(0,50, by=15)))

pred5 <- as.data.frame(predict(secondary_interact, secondary_total2, type="response", se.fit=TRUE))

secondary_total2$pred_prob <- pred5$fit
secondary_total2$pred_lower <- pred5$fit-(1.96*pred$se.fit)
secondary_total2$pred_upper <- pred5$fit+(1.96*pred$se.fit)

secondary_total2$lawrence <- as.factor(secondary_total1$lawrence)
secondary_total2$obergefell <- as.factor(secondary_total1$obergefell)

ggplot(secondary_total2, aes(x = evangelical_pop, y = pred_prob, color = lawrence)) + geom_smooth(method = "lm")
```

```{r}
## positive models

state_pos <- state_data %>% 
  filter(direction != "N" & direction != "M") 

positive_constants <- state_pos %>% 
  na.omit() %>% 
  summarize(pop_med = median(population_total), pollib_med = median(pollib_median), income_med = median(incomepcap), bowen1_med = median(std_bowen1), bowen2_med = median(std_bowen2), duration_med = median(duration), duration_sq_med = median(duration_sq), duration_cub_med = median(duration_cub), init_med = median(std_init_use), evang_med = median(evangelical_pop))


## positive primary model w/o category

## lawrence = 0, obergefell = 0
positive_primary_model <- glm(policy~lawrence + obergefell + nbrs_lag + population_total + pollib_median + incomepcap + std_bowen1 + std_bowen2 + duration + duration_sq + duration_cub + std_init_use + unified, data = state_pos, family = binomial)

primary_positive <-with(state_pos, data.frame(pollib_median=0.435309, population_total= 3642361, incomepcap = 30645.5, std_bowen1 = -0.03011499, std_bowen2 = 0.1457451, duration = 8, duration_sq = 64, duration_cub = 512, std_init_use = -0.4535984, unified = 1, nbrs_lag=seq(0, 3, by = 1), lawrence = 0, obergefell = 0))

pos_preds <- as.data.frame(predict(positive_primary_model, primary_positive, type="response", se.fit=TRUE))

primary_positive$pred_prob <- pos_preds$fit
primary_positive$pred_lower <- pos_preds$fit-(1.96*pred$se.fit)
primary_positive$pred_upper <- pos_preds$fit+(1.96*pred$se.fit)

primary_positive$lawrence <- as.factor(primary_positive$lawrence)
primary_positive$obergefell <- as.factor(primary_positive$obergefell)

## lawrence = 1, obergefell = 0

primary_positive1 <-with(state_pos, data.frame(pollib_median=0.435309, population_total= 3642361, incomepcap = 30645.5, std_bowen1 = -0.03011499, std_bowen2 = 0.1457451, duration = 8, duration_sq = 64, duration_cub = 512, std_init_use = -0.4535984, unified = 1, nbrs_lag=seq(0, 3, by = 1), lawrence = 0, obergefell = 0))

pos_preds1 <- as.data.frame(predict(positive_primary_model, primary_positive1, type="response", se.fit=TRUE))

primary_positive1$pred_prob <- pos_preds1$fit
primary_positive1$pred_lower <- pos_preds1$fit-(1.96*pred$se.fit)
primary_positive1$pred_upper <- pos_preds1$fit+(1.96*pred$se.fit)


primary_positive1$lawrence <- as.factor(primary_positive1$lawrence)
primary_positive1$obergefell <- as.factor(primary_positive1$obergefell)

## lawrence = 1, obergerfell = 1
primary_positive2 <-with(state_pos, data.frame(pollib_median=0.435309, population_total= 3642361, incomepcap = 30645.5, std_bowen1 = -0.03011499, std_bowen2 = 0.1457451, duration = 8, duration_sq = 64, duration_cub = 512, std_init_use = -0.4535984, unified = 1, nbrs_lag=seq(0, 3, by = 1), lawrence = 0, obergefell = 0))

pos_preds2 <- as.data.frame(predict(positive_primary_model, primary_positive2, type="response", se.fit=TRUE))

primary_positive2$pred_prob <- pos_preds2$fit
primary_positive2$pred_lower <- pos_preds2$fit-(1.96*pred$se.fit)
primary_positive2$pred_upper <- pos_preds2$fit+(1.96*pred$se.fit)


primary_positive2$lawrence <- as.factor(primary_positive2$lawrence)
primary_positive2$obergefell <- as.factor(primary_positive2$obergefell)


## secondary model w/o category

positive_secondary_model <- glm(policy~lawrence*evangelical_pop+ obergefell +nbrs_lag + population_total + pollib_median + incomepcap + std_bowen1 + std_bowen2 + duration + duration_sq + duration_cub + std_init_use + unified, data = state_pos, family = binomial)

<<<<<<< HEAD
=======
secondary_positive <-with(state_pos, data.frame(pollib_median=0.435309, population_total= 3642361, incomepcap = 30645.5, std_bowen1 = -0.03011499, std_bowen2 = 0.1457451, duration = 8, duration_sq = 64, duration_cub = 512, std_init_use = -0.4535984, unified = 1, nbrs_lag=seq(0, 3, by = 1), lawrence = 0, obergefell = 0, evangelical_pop = seq(0,50, by=10)))
>>>>>>> 50d425b926f093fa7fef65a3f74312236dc7743c

## lawrence = 0, obergefell = 0
secondary_positive <-with(state_pos, data.frame(pollib_median=0.435309, population_total= 3642361, incomepcap = 30645.5, std_bowen1 = -0.03011499, std_bowen2 = 0.1457451, duration = 8, duration_sq = 64, duration_cub = 512, std_init_use = -0.4535984, unified = 1, nbrs_lag=seq(0, 3, by = 1), lawrence = 0, obergefell = 0, evangelical_pop = seq(0,50, by=15)))

pos_preds4 <- as.data.frame(predict(positive_secondary_model, secondary_positive, type="response", se.fit=TRUE))

secondary_positive$pred_prob <- pos_preds4$fit
secondary_positive$pred_lower <- pos_preds4$fit-(1.96*pred$se.fit)
secondary_positive$pred_upper <- pos_preds4$fit+(1.96*pred$se.fit)

secondary_positive$lawrence <- as.factor(secondary_positive$lawrence)
secondary_positive$obergefell <- as.factor(secondary_positive$obergefell)


## lawrence = 1, obergefell = 0
secondary_positive1 <-with(state_pos, data.frame(pollib_median=0.435309, population_total= 3642361, incomepcap = 30645.5, std_bowen1 = -0.03011499, std_bowen2 = 0.1457451, duration = 8, duration_sq = 64, duration_cub = 512, std_init_use = -0.4535984, unified = 1, nbrs_lag=seq(0, 3, by = 1), lawrence = 0, obergefell = 0, evangelical_pop = seq(0,50, by=15)))

pos_preds5 <- as.data.frame(predict(positive_secondary_model, secondary_positive1, type="response", se.fit=TRUE))

secondary_positive1$pred_prob <- pos_preds5$fit
secondary_positive1$pred_lower <- pos_preds5$fit-(1.96*pred$se.fit)
secondary_positive1$pred_upper <- pos_preds5$fit+(1.96*pred$se.fit)

secondary_positive1$lawrence <- as.factor(secondary_positive1$lawrence)
secondary_positive1$obergefell <- as.factor(secondary_positive1$obergefell)

## lawrence = 1, obergefell = 1
secondary_positive2 <-with(state_pos, data.frame(pollib_median=0.435309, population_total= 3642361, incomepcap = 30645.5, std_bowen1 = -0.03011499, std_bowen2 = 0.1457451, duration = 8, duration_sq = 64, duration_cub = 512, std_init_use = -0.4535984, unified = 1, nbrs_lag=seq(0, 3, by = 1), lawrence = 0, obergefell = 0, evangelical_pop = seq(0,50, by=15)))

pos_preds6 <- as.data.frame(predict(positive_secondary_model, secondary_positive2, type="response", se.fit=TRUE))

secondary_positive2$pred_prob <- pos_preds6$fit
secondary_positive2$pred_lower <- pos_preds6$fit-(1.96*pred$se.fit)
secondary_positive2$pred_upper <- pos_preds6$fit+(1.96*pred$se.fit)

secondary_positive2$lawrence <- as.factor(secondary_positive2$lawrence)
secondary_positive2$obergefell <- as.factor(secondary_positive2$obergefell)

ggplot(secondary_positive2, aes(x=evangelical_pop, y=pred_prob, color=lawrence)) +geom_smooth(method="lm")
```


```{r}
## negative models

state_neg <- state_data %>% 
  filter(direction != "P" & direction != "M") 

negative_constants <- state_neg %>% 
  na.omit() %>% 
  summarize(pop_med = median(population_total), pollib_med = median(pollib_median), income_med = median(incomepcap), bowen1_med = median(std_bowen1), bowen2_med = median(std_bowen2), duration_med = median(duration), duration_sq_med = median(duration_sq), duration_cub_med = median(duration_cub), init_med = median(std_init_use), evang_med = median(evangelical_pop))


## primary model w/o category

negative_primary_model <- glm(policy~lawrence + obergefell + nbrs_lag + population_total + pollib_median + incomepcap + std_bowen1 + std_bowen2 + duration + duration_sq + duration_cub + std_init_use + unified, data = state_neg, family = binomial)

<<<<<<< HEAD

## lawrence = 0, obergefell = 0
=======
>>>>>>> 50d425b926f093fa7fef65a3f74312236dc7743c
primary_negative <-with(state_neg, data.frame(pollib_median=-0.168494, population_total=2933904, incomepcap = 28702, std_bowen1 = -0.3028264, std_bowen2 = 0.1504067, duration = 8, duration_sq = 64, duration_cub = 512, std_init_use = -0.4535984, unified = 1, nbrs_lag=seq(0, 3, by = 1), lawrence = 0, obergefell = 0))

neg_preds <- as.data.frame(predict(negative_primary_model, primary_negative, type="response", se.fit=TRUE))

primary_negative$pred_prob <- neg_preds$fit
primary_negative$pred_lower <- neg_preds$fit-(1.96*pred$se.fit)
primary_negative$pred_upper <- neg_preds$fit+(1.96*pred$se.fit)

primary_negative$lawrence <- as.factor(primary_negative$lawrence)
primary_negative$obergefell <- as.factor(primary_negative$obergefell)

## lawrence = 1, obergefell = 0
primary_negative1 <-with(state_neg, data.frame(pollib_median=-0.168494, population_total=2933904, incomepcap = 28702, std_bowen1 = -0.3028264, std_bowen2 = 0.1504067, duration = 8, duration_sq = 64, duration_cub = 512, std_init_use = -0.4535984, unified = 1, nbrs_lag=seq(0, 3, by = 1), lawrence = 1, obergefell = 0))

neg_preds1 <- as.data.frame(predict(negative_primary_model, primary_negative1, type="response", se.fit=TRUE))

primary_negative1$pred_prob <- neg_preds1$fit
primary_negative1$pred_lower <- neg_preds1$fit-(1.96*pred$se.fit)
primary_negative1$pred_upper <- neg_preds1$fit+(1.96*pred$se.fit)

primary_negative1$lawrence <- as.factor(primary_negative1$lawrence)
primary_negative1$obergefell <- as.factor(primary_negative1$obergefell)

## lawrence = 1, obergefell = 1
primary_negative2 <-with(state_neg, data.frame(pollib_median=-0.168494, population_total=2933904, incomepcap = 28702, std_bowen1 = -0.3028264, std_bowen2 = 0.1504067, duration = 8, duration_sq = 64, duration_cub = 512, std_init_use = -0.4535984, unified = 1, nbrs_lag=seq(0, 3, by = 1), lawrence = 1, obergefell = 0))

neg_preds2 <- as.data.frame(predict(negative_primary_model, primary_negative2, type="response", se.fit=TRUE))

primary_negative2$pred_prob <- neg_preds2$fit
primary_negative2$pred_lower <- neg_preds2$fit-(1.96*pred$se.fit)
primary_negative2$pred_upper <- neg_preds2$fit+(1.96*pred$se.fit)

primary_negative2$lawrence <- as.factor(primary_negative2$lawrence)
primary_negative2$obergefell <- as.factor(primary_negative2$obergefell)


## secondary model w/o category

negative_secondary_model <- glm(policy~lawrence * evangelical_pop+ obergefell+nbrs_lag + population_total + pollib_median + incomepcap + std_bowen1 + std_bowen2 + duration + duration_sq + duration_cub + std_init_use + unified, data = state_neg, family = binomial)


<<<<<<< HEAD
## lawrence = 0, obergefell = 0
secondary_negative <-with(state_neg, data.frame(pollib_median=-0.168494, population_total=2933904, incomepcap = 28702, std_bowen1 = -0.3028264, std_bowen2 = 0.1504067, duration = 8, duration_sq = 64, duration_cub = 512, std_init_use = -0.4535984, unified = 1, nbrs_lag=seq(0, 3, by = 1), lawrence = 0, obergefell = 0, evangelical_pop = seq(0,50, by=15)))
=======
secondary_negative <-with(state_neg, data.frame(pollib_median=-0.168494, population_total=2933904, incomepcap = 28702, std_bowen1 = -0.3028264, std_bowen2 = 0.1504067, duration = 8, duration_sq = 64, duration_cub = 512, std_init_use = -0.4535984, unified = 1, nbrs_lag=seq(0, 3, by = 1), lawrence = 1, obergefell = 0, evangelical_pop = seq(0,50, by=10)))
>>>>>>> 50d425b926f093fa7fef65a3f74312236dc7743c

neg_preds3 <- as.data.frame(predict(negative_secondary_model, secondary_negative, type="response", se.fit=TRUE))

secondary_negative$pred_prob <- neg_preds3$fit
secondary_negative$pred_lower <- neg_preds3$fit-(1.96*pred$se.fit)
secondary_negative$pred_upper <- neg_preds3$fit+(1.96*pred$se.fit)

secondary_negative$lawrence <- as.factor(secondary_negative$lawrence)
secondary_negative$obergefell <- as.factor(secondary_negative$obergefell)

## lawrence = 1, obergefell = 0
secondary_negative1 <-with(state_neg, data.frame(pollib_median=-0.168494, population_total=2933904, incomepcap = 28702, std_bowen1 = -0.3028264, std_bowen2 = 0.1504067, duration = 8, duration_sq = 64, duration_cub = 512, std_init_use = -0.4535984, unified = 1, nbrs_lag=seq(0, 3, by = 1), lawrence = 0, obergefell = 0, evangelical_pop = seq(0,50, by=15)))

neg_preds4 <- as.data.frame(predict(negative_secondary_model, secondary_negative1, type="response", se.fit=TRUE))

secondary_negative1$pred_prob <- neg_preds4$fit
secondary_negative1$pred_lower <- neg_preds4$fit-(1.96*pred$se.fit)
secondary_negative1$pred_upper <- neg_preds4$fit+(1.96*pred$se.fit)

secondary_negative1$lawrence <- as.factor(secondary_negative1$lawrence)
secondary_negative1$obergefell <- as.factor(secondary_negative1$obergefell)

## lawrence = 1, obergefell = 1
secondary_negative2 <-with(state_neg, data.frame(pollib_median=-0.168494, population_total=2933904, incomepcap = 28702, std_bowen1 = -0.3028264, std_bowen2 = 0.1504067, duration = 8, duration_sq = 64, duration_cub = 512, std_init_use = -0.4535984, unified = 1, nbrs_lag=seq(0, 3, by = 1), lawrence = 0, obergefell = 0, evangelical_pop = seq(0,50, by=15)))

neg_preds5 <- as.data.frame(predict(negative_secondary_model, secondary_negative2, type="response", se.fit=TRUE))

secondary_negative2$pred_prob <- neg_preds5$fit
secondary_negative2$pred_lower <- neg_preds5$fit-(1.96*pred$se.fit)
secondary_negative2$pred_upper <- neg_preds5$fit+(1.96*pred$se.fit)

secondary_negative2$lawrence <- as.factor(secondary_negative2$lawrence)
secondary_negative2$obergefell <- as.factor(secondary_negative2$obergefell)
```

```{r}
## interaction vary
secondary_interact <- glm(policy~lawrence*evangelical_pop+ obergefell + nbrs_lag + population_total + pollib_median + incomepcap + unified + std_bowen1 + std_bowen2 + duration + duration_sq + duration_cub + std_init_use, data = state_data, family = binomial)

secondary_negative <-with(secondary_interact, data.frame(pollib_median=-0.168494, population_total=2933904, incomepcap = 28702, std_bowen1 = -0.3028264, std_bowen2 = 0.1504067, duration = 8, duration_sq = 64, duration_cub = 512, std_init_use = -0.4535984, unified = 1, nbrs_lag=seq(0, 3, by = 1), lawrence = 0, obergefell = 0, evangelical_pop = seq(0,50, by=10)))

secondary_negative1 <-with(secondary_interact, data.frame(pollib_median=-0.168494, population_total=2933904, incomepcap = 28702, std_bowen1 = -0.3028264, std_bowen2 = 0.1504067, duration = 8, duration_sq = 64, duration_cub = 512, std_init_use = -0.4535984, unified = 1, nbrs_lag=seq(0, 3, by = 1), lawrence = 1, obergefell = 0, evangelical_pop = seq(0,50, by=10)))

secondary_negative<- rbind(secondary_negative, secondary_negative1)

neg_preds2 <- as.data.frame(predict(secondary_interact, secondary_negative, type="response", se.fit=TRUE))


secondary_negative$pred_prob <- neg_preds2$fit
secondary_negative$pred_lower <- neg_preds2$fit-(1.96*neg_preds2$se.fit)
secondary_negative$pred_upper <- neg_preds2$fit+(1.96*neg_preds2$se.fit)

secondary_negative$lawrence<- as.factor(secondary_negative$lawrence)

ggplot(secondary_negative, aes(x=evangelical_pop, y=pred_prob, color=lawrence)) +geom_smooth(method="lm")

```

```{r}
## interaction vary
secondary_interact <- glm(policy~lawrence*evangelical_pop+ obergefell + nbrs_lag + population_total + pollib_median + incomepcap + unified + std_bowen1 + std_bowen2 + duration + duration_sq + duration_cub + std_init_use, data = state_data, family = binomial)

secondary_negative <-with(secondary_interact, data.frame(pollib_median=-0.168494, population_total=2933904, incomepcap = 28702, std_bowen1 = -0.3028264, std_bowen2 = 0.1504067, duration = 8, duration_sq = 64, duration_cub = 512, std_init_use = -0.4535984, unified = 1, nbrs_lag=seq(0, 3, by = 1), lawrence = 0, obergefell = 0, evangelical_pop = seq(0,50, by=10)))

secondary_negative1 <-with(secondary_interact, data.frame(pollib_median=-0.168494, population_total=2933904, incomepcap = 28702, std_bowen1 = -0.3028264, std_bowen2 = 0.1504067, duration = 8, duration_sq = 64, duration_cub = 512, std_init_use = -0.4535984, unified = 1, nbrs_lag=seq(0, 3, by = 1), lawrence = 1, obergefell = 0, evangelical_pop = seq(0,50, by=10)))

secondary_negative<- rbind(secondary_negative, secondary_negative1)

neg_preds2 <- as.data.frame(predict(secondary_interact, secondary_negative, type="response", se.fit=TRUE))


secondary_negative$pred_prob <- neg_preds2$fit
secondary_negative$pred_lower <- neg_preds2$fit-(1.96*neg_preds2$se.fit)
secondary_negative$pred_upper <- neg_preds2$fit+(1.96*neg_preds2$se.fit)

secondary_negative$lawrence<- as.factor(secondary_negative$lawrence)

ggplot(secondary_negative, aes(x=evangelical_pop, y=pred_prob, color=lawrence)) +geom_smooth(method="lm")

```

