---
title: "Modeling3"
author: "Grace Rade"
date: "2023-02-24"
output: html_document
---
```{r}
library(tidyverse)
library(rio)
library(haven)
library(stargazer)
library(reader)
library(texreg)

state_data <- import("./datasets/risk_states4.csv")
```

```{r}
## Model 1 for primary hypothesis, do another one to control for nothing just our primary vars

primary_model <- glm(policy~lawrence + obergefell + nbrs_lag + population_total + pollib_median + incomepcap + std_bowen1 + std_bowen2 + duration + duration_sq + duration_cub + std_init_use + unified, data = state_data, family = binomial)

summary(primary_model)

#stargazer(primary_model, type="text", out ="model1.docx")
```

```{r}
## add the new evangelical data and then try to find the mean variable that breaks it

## interaction between evangelical*pre/post for the cases (separately)



secondary_model <- glm(policy~lawrence*evangelical_pop+obergefell+ nbrs_lag + population_total + pollib_median + incomepcap + std_bowen1 + std_bowen2 + duration + duration_sq + duration_cub + std_init_use + unified, data = state_data, family = binomial) 
```

```{r}
## just the court cases
simplest_model <- glm(policy~lawrence+ obergefell, data = state_data, family = binomial)
summary(simplest_model)


## just hte court cases and evangelical
simplest_model2 <- glm(policy~obergefell+lawrence*evangelical_pop, data = state_data, family = binomial)
summary(simplest_model2)


## just lawrence
law_only <- glm(policy~lawrence, data = state_data, family = binomial)
summary(law_only)

## jusr obergefell
ober_only <- glm(policy~obergefell, data = state_data, family = binomial)
summary(ober_only)

## lawrence and evangelical
law_evan <- glm(policy~lawrence+ evangelical_pop, data = state_data, family = binomial)
summary(law_evan)

## obergefell and evangelical
ober_evan <- glm(policy~obergefell+ evangelical_pop, data = state_data, family = binomial)
summary(ober_evan)
```

```{r}

## models for the positive laws
state_pos <- state_data %>% 
  filter(direction != "N" & direction != "M")

positive_simplest <- glm(policy~lawrence + obergefell, data = state_pos, family = binomial)
summary(positive_simplest)

positive_simplest2 <- glm(policy~lawrence + obergefell + evangelical_pop, data = state_pos, family = binomial)
summary(positive_simplest2)

positive_primary <- glm(policy~lawrence + obergefell + nbrs_lag + population_total + pollib_median + incomepcap + std_bowen1 + std_bowen2 + duration + duration_sq + duration_cub + std_init_use + unified, data = state_pos, family = binomial)

summary(positive_primary)

positive_secondary <- glm(policy~lawrence*evangelical_pop + obergefell + nbrs_lag + population_total + pollib_median + incomepcap + std_bowen1 + std_bowen2 + duration + duration_sq + duration_cub + std_init_use + unified, data = state_pos, family = binomial)

summary(positive_secondary)
```

```{r}
state_neg <- state_pos <- state_data %>% 
  filter(direction != "P" & direction != "M")

negative_simplest <- glm(policy~lawrence+obergefell, data = state_neg, family = binomial)
summary(negative_simplest)

negative_simplest2 <- glm(policy~lawrence+obergefell+evangelical_pop, data = state_neg, family = binomial)
summary(negative_simplest2)

negative_primary <- glm(policy~lawrence + obergefell + nbrs_lag + population_total + pollib_median + incomepcap + std_bowen1 + std_bowen2 + duration + duration_sq + duration_cub + std_init_use + unified, data = state_neg, family = binomial)

summary(negative_primary)

negative_secondary <- glm(policy~lawrence*evangelical_pop+ obergefell +nbrs_lag + population_total + pollib_median + incomepcap + std_bowen1 + std_bowen2 + duration + duration_sq + duration_cub + std_init_use + unified, data = state_neg, family = binomial)

summary(negative_secondary)
```

```{r}
## make it <3 beautiful <3

#stargazer(primary_model, secondary_model, simplest_model, simplest_model2, type="text", out ="simple_models.docx") ## gorgeous

#stargazer(law_only, law_evan, ober_only, ober_evan, type = "text", out = 'single_models.docx')

#stargazer(positive_primary, positive_secondary, positive_simplest,
#positive_simplest2, type = "text", out = "positive_models.docx")

#stargazer(negative_primary, negative_secondary, negative_simplest, negative_simplest2, type = "text", out = "negative_models.docx") 

## the positive and the negative models won't be pretty ugh
```

```{r}
stargazer(primary_model, simplest_model, positive_primary, negative_primary, type = "html", out = "primary_models2.html", column.labels = c("Full Primary ", "Reduced Primary ", "Positive Primary ", "Negative Primary "), covariate.labels = c("Lawrence", "Obergefell", "Neighbor Adoptions", " Population","Policy Liberalism","Per Capita Income", "Legislative Professionalism 1",
"Legislative Professionalism 2", "Duration", "Duration Sq.", "Duration Cub.", "Initiative Use", "Unified Government", "Intercept"), dep.var.labels = "Probability of Adoption", title = "Primary Model Results") ## change to HTML to render and take a screenshot

stargazer(secondary_model, simplest_model2, positive_secondary, negative_secondary, type = "html", out = "secondary_models2.html", column.labels = c("Full Secondary", "Reduced Secondary", "Positive Secondary", "Negative Secondary"), covariate.labels = c("Lawrence", "Evangelical Population", "Obergefell", "Neighbor Adoptions", " Population","Policy Liberalism","Per Capita Income", "Legislative Professionalism 1", "Legislative Professionalism 2", "Duration", "Duration Sq.", "Duration Cub.", "Initiative Use", "Unified Government", "Lawrence*Evangelical Population", "Intercept"), dep.var.labels = "Probability of Adoption", title = "Secondary Model Results") ## change to HTML to render and take a screenshot


```

